#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source ${APPLIANCE_DIR}/lib/lib-common
source ${APPLIANCE_DIR}/lib/lib-environment
source ${APPLIANCE_DIR}/lib/lib-interface
ROOT_DIR=${ADMIN_DIR}
source ${APPLIANCE_DIR}/etc/constant

render-upright-configuration()
{
    init-env-variables

    ! is-locked-local-env || restore-env
    ! is-locked-configuration-db || restore-configuration-db

    test ${APL_ROLE} == manager || return 0

    local id

    if test -s ${ABASE_DIR}/${MANAGER_GATEWAY_INDEX} ; then

	local in_uuid ip

	while read in_uuid id ip
	do
	    init-env-variables gateway ${id}

	    ! is-locked-local-env || restore-env
	    ! is-locked-configuration-db || restore-configuration-db
	done < ${ABASE_DIR}/${MANAGER_GATEWAY_INDEX}
    fi

    local dir=$(get-manager-context-rdir template)
    cd ${ABASE_DIR}/${dir}
    local templates=$(ls -1 2> /dev/null)

    for id in ${templates}
    do
	init-env-variables template ${id}

	! is-locked-local-env || restore-env
	! is-locked-configuration-db || restore-configuration-db
    done
}

# Main()

render-upright-configuration
