#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source /usr/local/lib/apl_functions

do-ha-action()
{
    test -n "${1}" || return 1
    local action=${1}

    case ${action} in
	failover)
	    echo -n "off" > ${RUN_DIR}/${HEALTH_STATE_FILENAME}
	    /etc/rc.d/init.d/health stop > /dev/null 2>&1
	    /etc/rc.d/init.d/keepalived stop > /dev/null 2>&1
	    apl_health_check ${$}
	    ;;
	active)
	    rm -f ${RUN_DIR}/${HEALTH_STATE_FILENAME}
	    /etc/rc.d/init.d/keepalived restart > /dev/null 2>&1
	    /etc/rc.d/init.d/health restart > /dev/null 2>&1
	    ;;
	*)
	    ;;
    esac
}

clean-exit()
{
    trap "" USR1 INT QUIT TERM

    local code=${1}
    wait
    manage-appliance-unlock
    exit ${code}
}

main()
{
    trap "clean-exit 100" USR1 INT QUIT TERM
    manage-appliance-lock
    do-ha-action "${@}"
    manage-appliance-unlock
}

# Main()

main "${@}"
