#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

squid-log-rotate()
{
    local pids

    pids=$(pidof squid 2> /dev/null)

    test ${?} -eq 0 || return 0
    test -n "${pids}" || return 0

    local wait_time=3
    local wait_tries=20
    local try=0

    while true
    do
	/etc/rc.d/init.d/squid rotate > /dev/null 2>&1
	test ${?} -ne 0 || break
	test ${try} -le ${wait_tries} || break
	sleep ${wait_time}
	((try++))
    done
}

# Main()

squid-log-rotate
