#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source /usr/local/lib/apl_common

raid-fail()
{
    test -n "${1}" || return 11
    local hd=${1}

    local pp=$(get-partition-prefix ${hd})

    test -b ${hd}${pp}${RAID_PARTITION_NB} || return 13
    mdadm --quiet /dev/md${RAID_MD_NB} --fail ${hd}${pp}${RAID_PARTITION_NB}
}

main()
{
    test -n "${1}" || return 11
    local hd=${1}
    test ${hd:0:5} == "/dev/" || hd="/dev/${hd}"
    
    raid-fail ${hd}
}

# Main()

main "${@}"
