#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source ${LOCAL_DIR}/lib/apl_functions
source ${BASE_DIR}/${ADMIN_NAME}/${ENV_RDIR}/${ENV_CURRENT_NAME}

test-ldap-auth()
{
    test -n "${1}" || return 1
    test-current-ldap-auth-state || return 3
    local lg=${1}
    local ps=${2}

    local base_name=${0/*\/}
    local tmp_error_file=/tmp/${base_name}.${$}
    local ldap_timeout=10
    local bind_opt

    local sldap urls=$(print-ldap-urls "${CURRENT_LDAP_SERVER_LIST}")
    ! test-sldap "${CURRENT_LDAP_SERVER_LIST}" || sldap=" -Z"

    if test ${CURRENT_LDAP_BIND_MODE} == True -a -s ${PROXY_DIR}${LDAP_DIR}/${LDAP_PASSWD} ; then
	bind_opt=" -D ${CURRENT_LDAP_BIND_DN} -W ${LDAP_DIR}/${LDAP_PASSWD}"
    fi

    local password_attribute_opt filter_opt

    test -z "${CURRENT_LDAP_PASSWORD}" || password_attribute_opt=" -U ${CURRENT_LDAP_PASSWORD}"

    if test -z "${CURRENT_LDAP_FILTER}" ; then
	filter_opt="${CURRENT_LDAP_LOGIN}=%s"
    else
	filter_opt="(&(${CURRENT_LDAP_FILTER})(${CURRENT_LDAP_LOGIN}=%s))"
    fi

    local result=$(echo "${lg}" "${ps}" | chroot ${PROXY_DIR} /libexec/basic_ldap_auth -v 3 -c ${LDAP_CONNECTION_TIMEOUT} -t ${ldap_timeout} -s sub -a never -R -b "${CURRENT_LDAP_BASE_DN}" -f "${filter_opt}"${password_attribute_opt}${bind_opt}${sldap} ${urls} 2> ${tmp_error_file})

    local error_message=$(cat ${tmp_error_file} 2> /dev/null)
    error_message=${error_message/basic_ldap_auth: }
    rm -f ${tmp_error_file}
    
    if test "${result:0:2}" == OK ; then
	echo OK
	return 0
    else
	if test -z "${error_message}" ; then
	    echo KO
	else
	    echo "KO: ${error_message/basic_ldap_auth}"
	fi
	return 11
    fi
}

# Main()

test-ldap-auth "${@}"
