#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source ${HARD_DIR}/model.conf
source ${LOCAL_DIR}/lib/apl_common

change-apl-password()
{
    test -n "${1}" || return 1
    local user=${1}
    local password=${2}

    test -d ${HOME_DIR}/${user} || return 11
    test -d ${BASE_DIR}/${user} || return 13

    local password_file=/tmp/.cg-internal-cp.${$}

    echo ${user}:${password} > ${password_file}

    if test ${user} == ${ADMIN_NAME} ; then

	local sapassword rpassword

	if test -n "${password}" ; then
	    sapassword=${password}
	    local level=$(get-usage-level)
	    rpassword=${password}${level}
	fi

	echo ${SUPERADMIN_NAME}:${sapassword}
	echo root:${rpassword}
    fi >> ${password_file}

    chpasswd < ${password_file}
    rm -f ${password_file}

    echo ${password} | openssl dgst -sha1 2> /dev/null > ${password_file}

    install -m 600 -o ${user} -g ${GROUP_NAME} ${password_file} ${BASE_DIR}/${user}/.passwd.sha1
    install -m 600 -o ${user} -g ${GROUP_NAME} ${password_file} ${BASE_DIR}/${user}/.htpasswd.sha1
    rm -f ${password_file}

    chroot ${ADMIN_DIR} /bin/htpasswd -Bb /${HARD_DIR_NAME}/.htpasswd ${user} "${password}" > /dev/null 2>&1

    touch ${ETC_DIR}/shadow /etc/shadow

    rm -f ${ETC_DIR}/shadow-
    rm -f /etc/shadow-
}

change-ea-vpnsubscr-password()
{
    [ ! -f /etc/sysconfig/vpnsubscr ]  || source /etc/sysconfig/vpnsubscr
    [ "${EMBEDDED_VPNSUBSCR}" == yes ] || return 0

    apl_ea_vpnsubscr_change_password ${ADMIN_NAME} "${1}"
}

change-ea-password()
{
    change-ea-vpnsubscr-password "${@}"
}

main()
{
    change-apl-password "${@}"
    # change-ea-password "${@}"
}

# Main()

main "${@}"
