#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source ${HARD_DIR}/model.conf
source ${LOCAL_DIR}/lib/apl_common

gen-stop-srv()
{
    local srv

    unset STOP_SERVICES

    for srv in ${START_SERVICES}
    do
	STOP_SERVICES="${srv} ${STOP_SERVICES}"
    done

    local len=${#STOP_SERVICES}
    ((len--))
    STOP_SERVICES="${STOP_SERVICES:0:${len}}"
}

start-srv()
{
    local mode=${1}
    test -n "${mode}" || mode=all

    local srv file

    for srv in ${START_SERVICES}
    do
	case ${mode} in
	    daemon-only)
		! member "${BASIC_NETWORK_SERVICES}" "${srv}" || continue
		;;

	    network-only)
		member "${BASIC_NETWORK_SERVICES}" "${srv}" || continue
		;;
	    
	    *)
		;;
	esac

	for file in /etc/rc.d/rcS.d/S[0-9][0-9]${srv} /etc/rc.d/rc3.d/S[0-9][0-9]${srv}
	do
	    if test -f ${file} ; then
		/etc/rc.d/init.d/${srv} start
		break
	    fi
	done
    done
}

ifstart-srv()
{
    local srv file

    for srv in ${IFSTART_SERVICES}
    do
	for file in /etc/rc.d/rc3.d/S[0-9][0-9]${srv}
	do
	    if test -f ${file} ; then
		/etc/rc.d/init.d/${srv} status > /dev/null
		if test ${?} -ne 0 ; then
		    /etc/rc.d/init.d/${srv} start
		    break
		fi
	    fi
	done
    done
}

status-srv()
{
    local srv
    for srv in ${APPLIANCE_SERVICES}
    do
	/etc/rc.d/init.d/${srv} status
    done
}

stop-srv()
{
    local mode=${1}
    test -n "${mode}" || mode=all
    
    gen-stop-srv

    local srv file

    for srv in ${STOP_SERVICES}
    do
	case ${mode} in
	    daemon-only)
		! member "${BASIC_NETWORK_SERVICES}" "${srv}" || continue
		;;

	    network-only)
		member "${BASIC_NETWORK_SERVICES}" "${srv}" || continue
		;;

	    *)
		;;
	esac
	    
	for file in /etc/rc.d/rc0.d/K[0-9][0-9]${srv}
	do
	    if test -f ${file} ; then
		/etc/rc.d/init.d/${srv} stop
		break
	    fi
	done
    done
}

# Main()

APPLIANCE_SERVICES="ocspd iked freshclam clamd slapd c-icap squid httpd htcacheclean keepalived crond anacron path health"
ADMIN_SERVICES="sshd ${WADMIND_NAME} snmpd"
BASIC_NETWORK_SERVICES="iptables localnet cloud-network waagent network sysnetctl tc"
NETWORK_SERVICES="${BASIC_NETWORK_SERVICES} dhcpd named ntpd"
START_SERVICES="${NETWORK_SERVICES} ${ADMIN_SERVICES} ${APPLIANCE_SERVICES}"
IFSTART_SERVICES="${ADMIN_SERVICES} ${APPLIANCE_SERVICES}"

test -n "${1}" || return 0
ACTION=${1}
MODE=${2}

case ${ACTION} in
    start)
	start-srv ${MODE}
	;;
    ifstart)
	ifstart-srv ${MODE}
	;;
    stop)
	stop-srv ${MODE}
	;;
    restart)
	stop-srv ${MODE}
	start-srv ${MODE}
	;;
    status)
	status-srv ${MODE}
	;;
    *)
	exit 1
	;;
esac
