#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source ${LOCAL_DIR}/lib/apl_common

convert-date()
{
    test -n "${1}" || return 1
    local number=${1}
    local scale=${2}

    case "${scale}" in
	d|da|day|days)
	    date=$(get-date-from-epoch-days ${number})
	    ;;
	s|se|sec|seco|secon|second|seconds)
	    date=$(get-date-from-epoch-seconds ${number})
	    ;;
	*)
	    date=$(get-date-from-epoch-seconds ${number})
	    ;;
    esac

    echo ${date}
}

# Main()

convert-date "${@}"
