#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${LOCAL_DIR}/lib/apl_functions
source ${BASE_DIR}/${ADMIN_NAME}/${ENV_RDIR}/${ENV_CURRENT_NAME}

suspend-access-before()
{
    apl_apply_cancel < /dev/console > /dev/null 2> /dev/null
    touch /var/lock/apl_apply
}

suspend-access-after()
{
    rm -f /var/lock/apl_apply
}

main()
{
    set-usage-parameters
    set-proxy-parameters-cur

    manage-appliance-lock apl_verify_usage

    verify-usage active  > /dev/null 2>&1
    local ret=${?}

    manage-appliance-unlock apl_verify_usage
    return ${ret}
}

# Main()

main "${@}"
