#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role

apl-update-av-extended-create-downloaded-sz()
{
    local tmp_file=/tmp/av-extended-pack-file-info.${$}
    local rights links user group sz rest

    ls -l /var/tmp/${AV_EXTENDED_PACK_NAME}.tar.gz > ${tmp_file} 2> /dev/null
    if test ${?} -eq 0  ; then
	read rights links user group sz rest < ${tmp_file}
       test -n "${sz}" || sz=0
       echo -n ${sz} > ${RUN_DIR}/${AV_EXTENDED_PACK_DOWNLOADED_SZ_FILENAME}
    fi
}

# Main()

apl-update-av-extended-create-downloaded-sz "${@}"
