#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source ${ABASE_DIR}/${ENV_RDIR}/${ENV_CURRENT_NAME}

gateway-notification()
{
    test -n "${1}" || return 1
    test -n "${2}" || return 2
    local action=${1}
    local gateway_ip=${2}
    
    local event event_description description

    case ${action} in
	add)
	    event=Added
            event_description="The gateway has been added to the routing table."
	    ;;
        del)
	    event=Removed
            event_description="The gateway has been removed from the routing table."
	    ;;
	*)
	    event=Changed
	    event_description="The description is unknown."
	    ;;
    esac

    description="Gateway ${gateway_ip} ${event}: ${event_description}"

    logger -p daemon.alert -t apl_gateway_monitor -- "${description}"
    ${LOCAL_DIR}/bin/apl_rlogger "${description}"
    test "${CURRENT_ADMIN_SNMP}" == True || return 0
    ${LOCAL_DIR}/bin/apl_snmp_trap 16 "${event}" "${gateway_ip}" "${description}" > /dev/null 2>&1
}

# Main()

gateway-notification "${@}"
