#!/bin/bash

###########################################################################
#
# MODULE:       Scripts
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source ${LOCAL_DIR}/lib/apl_common
source ${LOCAL_DIR}/lib/apl_admin
source ${APPLIANCE_DIR}/lib/lib-interface

manage-password()
{
    test -n "${1}" || return 1
    test -n "${2}" || return 2
    local user=${1}
    local input=${2}

    case ${input} in

	console)
	    local passwd_file=${BASE_DIR}/${user}/.passwd
	    test -f ${passwd_file} || return 3

	    chpasswd < ${passwd_file}
	    rm -f ${passwd_file}
	    ;;

	wadmin)
	    test ! -f ${WEB_SERVER_DIR}/etc/.htpasswd || update-waudit-htpasswd
	    ;;

	*)
	    ;;
    esac

}

main()
{
    test -n "${1}" || return 1
    test -n "${2}" || return 2
    local user=${1}
    local input=${2}

    case ${input} in

	console|wadmin)
	    manage-password ${user} ${input}
	    ;;
	login)
	    manage-password ${user} console
	    manage-password ${user} wadmin
	    ! is-first-login ${user} || rm -f ${BASE_DIR}/${user}/${FIRST_LOGIN}
	    ;;
	*)
	    ;;
    esac
}

# Main()

main "${@}"
