timeout 60;
retry 3;
select-timeout 0;
reboot 10;
backoff-cutoff 15;
initial-interval 10;
initial-delay 0;

request;
require subnet-mask;

also request subnet-mask,
     	     broadcast-address,
	     routers,
	     domain-name-servers;
