#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

load-timezones()
{
    unset AREAS
    unset TIMEZONES

    local tz area i=0 j=0

    while read tz
    do
	test -n "${tz}" || continue
	
	TIMEZONES[${i}]=${tz}
	area=${tz/\/*/}
	
	if test ${i} -eq 0 ; then
	    AREAS[${i}]=${area}
	else
	    if test "${AREAS[${j}]}" != "${area}" ; then
		((j++))
		AREAS[${j}]=${area}
	    fi
	fi
	((i++))
    done < ${ETC_DIR}/timezones

    TIMEZONES_NB=${i}
    AREAS_NB=$[${j} + 1]
}
