#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

site-name-exist()
{
    test -n "${1}" || return 1
    local in_name=${1}

    local name
    local elt range i=0

    for elt in ${RWEB_SITE_LIST}
    do
	range=$[${i} % 5]
	case ${range} in
	    0)
		name=${elt}
		;;
	    1|2|3)
		;;
	    4)
		test ${name} != ${in_name} || return 0
		;;
	    *)
		return 1
		;;
	esac
	((i++))
    done

    return 11
}

site-ip-exist()
{
    test -n "${1}" || return 1
    test -n "${2}" || return 2
    local in_name=${1}
    local in_ip=${2}

    local name ip
    local elt range i=0

    for elt in ${RWEB_SITE_LIST}
    do
	range=$[${i} % 5]
	case ${range} in
	    0)
		name=${elt}
		;;
	    2)
		ip=${elt}
		;;
	    1|3)
		;;
	    4)
		test ${name} != ${in_name} -o ${ip} != ${in_ip} || return 0
		;;
	    *)
		return 1
		;;
	esac
	((i++))
    done

    return 11
}

site-name-ip-exist()
{
    test -n "${1}" || return 1
    test -n "${2}" || return 2
    local in_name=${1}
    local in_ip=${2}

    local name ip
    local elt range i=0

    for elt in ${RWEB_SITE_LIST}
    do
	range=$[${i} % 5]
	case ${range} in
	    0)
		name=${elt}
		;;
	    2)
		ip=${elt}
		;;

	    1|3)
		;;
	    4)
		test "${name} ${ip}" != "${in_name} ${in_ip}" || return 0
		;;
	    *)
		return 1
		;;
	esac
	((i++))
    done

    return 11
}

get-site-name-list()
{
    test -n "${1}" || return 0
    local rweb_site_list=${1}

    local elt i=0 range
    local name

    local result

    for elt in ${rweb_site_list}
    do
	range=$[${i} % 5]
	case ${range} in
	    0)
		name=${elt}
		;;
	    1|2|3)
		;;
	    4)
		if ! member "${result}" ${name} ; then
		    result="${result} ${name}"
		fi
		;;
	    *)
		return 255
		;;
	esac
	((i++))
    done

    echo ${result:1}
}

get-https-site-name-list()
{
    test -n "${1}" || return 0
    local rweb_site_list=${1}

    local elt i=0 range
    local name

    local result

    for elt in ${rweb_site_list}
    do
	range=$[${i} % 5]
	case ${range} in
	    0)
		name=${elt}
		;;
	    1)
		protocol=${elt}
		;;
	    2|3)
		;;
	    4)
		if test ${protocol} == https ; then
		    if ! member "${result}" ${name} ; then
			result="${result} ${name}"
		    fi
		fi
		;;
	    *)
		return 255
		;;
	esac
	((i++))
    done

    echo ${result:1}
}
