#!/bin/bash

###########################################################################
#
# MODULE:       Configurator
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source /usr/local/lib/apl_functions

clean-exit()
{
    trap "" USR1 INT QUIT TERM

    local code=${1}
    wait
    clean-backup-files
    manage-appliance-unlock
    backup-log-abort
    backup-log "Aborting the Backup operation"
    backup-log-ret ${?}
    exit ${code}
}

main()
{
    trap "clean-exit 100" USR1 INT QUIT TERM
    apl-backup "${@}"
}

# Main()

main "${@}"
