conn %default
    compress = no
    dpddelay = 30s
    forceencaps = yes
    fragmentation = yes
    installpolicy = yes
    keyingtries = %forever
    leftallowany = no
    leftfirewall = no
    lefthostaccess = no
    keyexchange = ikev2
    mobike = yes
    modeconfig = pull
    reauth = yes
    rekey = yes
    rekeyfuzz = 75%
    replay_window = -1
    sha256_96 = no
    type = tunnel
    mediation = no

conn _inter-site
    closeaction = restart
    dpdaction = restart
    ikelifetime = 10h
    margintime = 10m

conn _remote-access
    closeaction = clear
    dpdaction = clear
    ikelifetime = 2h
    margintime = 5m

conn _client
    closeaction = restart
    dpdaction = restart
    ikelifetime = 5h
    margintime = 10m

include ipsec.global.conf
include ipsec.ca.conf
