load-tester {
    addrs_keep = no
    addrs_prefix = -1
    ca_dir =
    child_rekey = 600
    crl =
    delay = 0
    delete_after_established = no
    digest = sha1
    dpd_delay = 0
    dynamic_port = 0
    eap_password = miTest1ngP@ssword
    enable = no
    esp = aes128-sha1
    fake_kernel = no
    ike_rekey = 0
    init_limit = 0
    initiator = 0.0.0.0
    initiator_auth = pubkey
    initiator_id =
    initiator_match =
    initiator_tsi =
    initiator_tsr =
    initiators = 0
    issuer_cert =
    issuer_key =
    iterations = 1
    load = no
    mode = tunnel
    pool =
    preshared_key = miTest1ngPreSh@redKey
    proposal = aes128-sha1-modp768
    request_virtual_ip = no
    responder = 127.0.0.1
    responder_auth = pubkey
    responder_id =
    responder_tsi = initiator_tsi
    responder_tsr = initiator_tsr
    shutdown_when_complete = no
    socket =
    version = 0

    addrs {
	eth1 = 172.19.20.0/24	  
    }
}
