#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-admin-user()
{
    local entry_pos user_pos password_pos del_pos pos=0
    local password

    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    while test ${pos} -lt ${ATTRIBUTE_NB}
    do
	entry_pos=${pos}
	user_pos=$[${pos} + 1]
	password_pos=$[${pos} + 2]
	del_pos=$[${pos} + 3]

	[[ "${ATTRIBUTES[${del_pos}]}" =~ ^del_[0-9]+$ ]]
	if test ${?} -ne 0 ; then
	    if test "${VALUES[${entry_pos}]}" == anew -a -n "${VALUES[${user_pos}]}" ; then
		password=${VALUES[${password_pos}]}
		echo "admin user add '${VALUES[${user_pos}]}' '${password}'" >> ${transaction}
	    fi
	    pos=$[${pos} + 3]
	else
	    echo "admin user del '${VALUES[${user_pos}]}'" >> ${transaction}
	    pos=$[${pos} + 4]
	fi
    done
    
    execute-transaction ${transaction}
}

# Main()

set-admin-user
