#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-bonding()
{
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    ! gui-contextual-is-allowed || echo "link bond external raz" >> ${transaction}
    echo "link bond internal raz"  >> ${transaction}
    ! gui-contextual-is-allowed || echo "link bond auxiliary raz" >> ${transaction}

    if gui-contextual-is-allowed ; then

	local i=0

	while test "${ATTRIBUTES[${i}]}" != internal
	do
	    echo "link bond external add ${VALUES[${i}]}" >> ${transaction}
	    ((i++))
	done

	while test "${ATTRIBUTES[${i}]}" != auxiliary
	do
	    echo "link bond internal add ${VALUES[${i}]}" >> ${transaction}
	    ((i++))
	done

	if test "${VALUES[${i}]}" != none ; then
	    for ((j=i ; j<ATTRIBUTE_NB ; j++))
	    do
		echo "link bond auxiliary add ${VALUES[${j}]}" >> ${transaction}
	    done
	fi

    else
	for ((i=0 ; j<ATTRIBUTE_NB ; j++))
	do
	    echo "link bond internal add ${VALUES[${i}]}" >> ${transaction}
	    ((i++))
	done
    fi

    execute-transaction ${transaction}
}

set-bonding
