#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-mode-network()
{
    local i mode

    local dhcp=off
    local dns=off
    local ftppassive=off
    local ha=off
    local qos=off
    local router=off
    local snat=off
    local tnat=off
    local tweb=off
    local vlan=off

    for ((i=1 ; i<${ATTRIBUTE_NB} ; i++))
    do
	mode=${ATTRIBUTES[${i}]:5}
	local ${mode}=on
    done

    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}

    if gui-contextual-is-allowed ; then

	echo mode dhcp ${dhcp}		 > ${transaction}
	echo mode dns ${dns}		>> ${transaction}
	echo mode ha ${ha}		>> ${transaction}
    fi

    echo mode ftppassive ${ftppassive}  >> ${transaction}

    if gui-contextual-is-allowed ; then

	echo mode qos ${qos}		>> ${transaction}
	echo mode router ${router}		>> ${transaction}
	echo mode snat ${snat}		>> ${transaction}
	echo mode tnat ${tnat}		>> ${transaction}
	echo mode tweb ${tweb}		>> ${transaction}
	echo mode vlan ${vlan}		>> ${transaction}
    fi

    execute-transaction ${transaction}
}

set-mode-network
