#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-qos-shape-router()
{
    local pos=0 entry_pos del_pos
    local rule_id_pos dev_pos protocol_pos src_ip_pos src_port_pos dscp_pos dst_ip_pos dst_port_pos ingress_qos_pos egress_qos_pos
    local entry_type rule_id dev protocol src_ip src_port dscp dst_ip dst_port ingress_qos egress_qos
    local old_rule_id prev_rule_id rule location position new_list
    local del_array insert_array add_array move_array
    declare -a del_array insert_array add_array move_array
    local del_nb=0 insert_nb=0 add_nb=0 move_nb=0 i

    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    while test ${pos} -lt ${ATTRIBUTE_NB}
    do
	entry_pos=${pos}
	rule_id_pos=$[${pos} + 1]
	dev_pos=$[${pos} + 2]
	protocol_pos=$[${pos} + 3]
	src_ip_pos=$[${pos} + 4]
	src_port_pos=$[${pos} + 5]
	ingress_qos_pos=$[${pos} + 6]
	dscp_pos=$[${pos} + 7]
	dst_ip_pos=$[${pos} + 8]
	dst_port_pos=$[${pos} + 9]
	egress_qos_pos=$[${pos} + 10]
	del_pos=$[${pos} + 11]

	entry_type=${VALUES[${entry_pos}]}
	rule_id=${VALUES[${rule_id_pos}]}
	dev=${VALUES[${dev_pos}]}
	protocol=${VALUES[${protocol_pos}]}
	src_ip=${VALUES[${src_ip_pos}]} ; src_ip=${src_ip// /}
	src_port=${VALUES[${src_port_pos}]}
	ingress_qos=${VALUES[${ingress_qos_pos}]}
	dscp=${VALUES[${dscp_pos}]}
	dst_ip=${VALUES[${dst_ip_pos}]} ; dst_ip=${dst_ip// /}
	dst_port=${VALUES[${dst_port_pos}]}
	egress_qos=${VALUES[${egress_qos_pos}]}
	
	[[ "${ATTRIBUTES[${del_pos}]}" =~ ^del_[0-9]+$ ]]
	if test ${?} -eq 0 ; then
	    del_array[${del_nb}]="${rule_id}"
	    ((del_nb++))
	    pos=$[${pos} + 12]
	else
	    if test -n "${rule_id}" ; then
		if test "${entry_type}" == anew -o "${entry_type}" == inew ; then
		    test -n "${src_ip}" || src_ip=any
		    test -n "${src_port}" || src_port=any
		    test -n "${ingress_qos}" || ingress_qos=100%
		    test -n "${dst_ip}" || dst_ip=any
		    test -n "${dst_port}" || dst_port=any
		    test -n "${egress_qos}" || egress_qos=100%
		    
		    rule="${rule_id} ${dev} ${protocol} ${src_ip} ${src_port} ${ingress_qos} ${dst_ip} ${dst_port} ${egress_qos} ${dscp}"
		    
		    new_list="${new_list} ${rule_id}"
		    
		    case "${entry_type}" in
			anew)
			    add_array[${add_nb}]="${rule}"
			    ((add_nb++))
			    ;;
			inew)
			    insert_array[${insert_nb}]="${rule}"
			    ((insert_nb++))
			    ;;
			*)
			    ;;
		    esac
		elif test "${entry_type:0:4}" == move ; then
		    position=${entry_type:4}
		    move_array[${move_nb}]="${rule_id}:${position}:${prev_rule_id}"
		    ((move_nb++))
		elif test "${entry_type}" == old ; then
		    old_rule_id=${rule_id}

		    for ((i=0 ; i<insert_nb ; i++))
		    do
			echo "qos shape router 'insert:${rule_id}' '${insert_array[${i}]}'" >> ${transaction}
		    done
		    unset insert_array
		    insert_nb=0
		fi
	    fi
	    pos=$[${pos} + 11]
	fi
	prev_rule_id=${rule_id}
    done

    new_list=${new_list:1}

    for ((i=0 ; i<insert_nb ; i++))
    do
	echo "qos shape router 'insert:${rule_id}' '${insert_array[${i}]}'" >> ${transaction}
    done

    if test -n "${old_rule_id}" ; then
	rule_id=${old_rule_id}
	for ((i=0 ; i<add_nb ; i++))
	do
	    echo "qos shape router 'add:${rule_id}' '${add_array[${i}]}'" >> ${transaction}
	    rule_id=${add_array[${i}]/ *}
	done
    else
	for ((i=0 ; i<add_nb ; i++))
	do
	    echo "qos shape router add '${add_array[${i}]}'" >> ${transaction}
	done
    fi

    for ((i=0 ; i<move_nb ; i++))
    do
	location=${move_array[${i}]}
	rule_id=${location/:*}
	prev_rule_id=${location/*:}

	if test -z "${prev_rule_id}" ; then
	    position=${location#*:}
	    position=${position/:*}
	    echo "qos shape router 'move:${position}' '${rule_id}'" >> ${transaction}
	else
	    
	    echo "qos shape router 'move:+${prev_rule_id}' '${rule_id}'" >> ${transaction}
	fi
    done

    for ((i=0 ; i<del_nb ; i++))
    do
	! member "${new_list}" ${del_array[${i}]} || continue
	echo "qos shape router del '${del_array[${i}]}'" >> ${transaction}
    done

    execute-transaction ${transaction}
}

set-qos-shape-router
