#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-waf-rweb-bypass-application()
{
    local pos=0 entry_pos name_pos application_pos del_pos
    local application

    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    while test ${pos} -lt ${ATTRIBUTE_NB}
    do
	entry_pos=${pos}
	name_pos=$[${pos} + 1]
	application_pos=$[${pos} + 2]
	del_pos=$[${pos} + 3]
	
	[[ "${ATTRIBUTES[${del_pos}]}" =~ ^del_[0-9]+$ ]]
	if test ${?} -ne 0 ; then
	    if test "${VALUES[${entry_pos}]}" == anew -a -n "${VALUES[${name_pos}]}" ; then
		application=${VALUES[${application_pos}]}
		test -z "${application}" || echo "waf rweb bypass application '${VALUES[${name_pos}]}' set '${application}'" >> ${transaction}
	    fi
	    pos=$[${pos} + 3]
	else
	    echo "waf rweb bypass application '${VALUES[${name_pos}]}' raz" >> ${transaction}
	    pos=$[${pos} + 4]
	fi
    done

    execute-transaction ${transaction}
}

# Main()

set-waf-rweb-bypass-application
