#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-rweb-balancer()
{
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    local site_name=${VALUES[0]}
    local algorithm=${VALUES[1]}

    local sticky mode cookie

    if test ${ATTRIBUTES[2]} == sticky ; then
	if test ${VALUES[2]} == on ; then
	    sticky=sticky
	    mode=${VALUES[3]}
	    cookie=${VALUES[4]}
	    if test -z "${cookie}" ; then
		echo "rweb balancer ${site_name} ${algorithm} sticky ${mode}" > ${transaction}
	    else
		echo "rweb balancer ${site_name} ${algorithm} sticky ${mode} ${cookie}" > ${transaction}
	    fi
	fi
    else
	echo "rweb balancer ${site_name} ${algorithm} nosticky" > ${transaction}
    fi

    execute-transaction ${transaction}
}

set-rweb-balancer
