#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-cache-size()
{
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    echo "cache object '${VALUES[0]}' '${VALUES[1]}'" >> ${transaction}

    if test "${VALUES[2]}" == off ; then
	echo "cache bigobject off" >> ${transaction}
    else
	if test -n "${VALUES[3]}" -a -n "${VALUES[4]}" ; then
	    echo "cache bigobject on '${VALUES[3]}' '${VALUES[4]}'" >> ${transaction}
	fi
    fi

    execute-transaction ${transaction}
}

set-cache-size
