#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

gui-set-password-login()
{
    test "${ATTRIBUTES[0]}" == password1 || return 0
    test "${ATTRIBUTES[1]}" == password2 || return 0

    local do_logout=no

    local new_pass1=${VALUES[0]}
    local new_pass2=${VALUES[1]}

    if test -z "${new_pass1}" -o -z "${new_pass2}" ; then
	gen-gui-error 1
	return 0
    fi

    if test "${new_pass1}" == "${new_pass2}" ; then
	local transaction=/tmp/${TRANSACTION_FILE}.login.${REMOTE_USER}.${$}
	rm -f ${transaction}
	echo "password login nil '${new_pass1}'" >> ${transaction}
	execute-transaction ${transaction}

	if test ${do_logout} == yes ; then
	    logout-page
	fi
	return 0
    else
	gen-gui-error 4
	return 0
    fi
}

gui-set-admin-2fa()
{
    test ${USER} != ${ADMIN_NAME} || return 0
    is-admin-2fa-enabled || return 0
    ! is-admin-2fa-is-running ${USER} || return 0
    execute-command "admin internal 2fa-initialise yes"
}

gui-set-password-login
gui-set-admin-2fa
