#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-vpnipsec-authenticate()
{
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    local ips ip

    if test "${VALUES[0]}" == psk ; then
	if test "${VALUES[1]}" == no ; then
	    echo "vpnipsec authenticate '${VALUES[0]}' '${VALUES[2]}'" > ${transaction}
	else
	    echo "vpnipsec authenticate '${VALUES[0]}' 'auto'" > ${transaction}
	fi
    elif test -n "${VALUES[3]}" ; then
	echo "vpnipsec authenticate '${VALUES[0]}' '${VALUES[3]}' '${VALUES[4]}'" > ${transaction}
    fi

    ips=${VALUES[5]}
    ips=${ips//,/ }

    echo "vpnipsec nat public raz" >> ${transaction}

    for ip in ${ips}
    do
	echo "vpnipsec nat public add ${ip}" >> ${transaction}
    done >> ${transaction}

    execute-transaction ${transaction}
}

set-vpnipsec-authenticate
