#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-waf-rweb-generic()
{
    test "${ATTRIBUTES[0]}" != "site_select" || return 0

    set-generic-rule-table

    local filter var
    local i len=${#WAF_GENERIC_FILTER_ID[@]}

    for ((i=0;i<len;i++))
    do
	filter=${WAF_GENERIC_FILTER_ID[${i}]}	
	local ${filter}=off
    done

    for ((i=1 ; i<${ATTRIBUTE_NB} ; i++))
    do
	filter=${ATTRIBUTES[${i}]:4}
	local ${filter}=on
    done

    local name=${VALUES[0]}
    if test ${ATTRIBUTES[1]} == "waf_inherit" ; then
	execute-command "waf rweb generic ${name} inherit"
	return 0
    fi


    for ((i=1 ; i<${ATTRIBUTE_NB} ; i++))
    do
	filter=${ATTRIBUTES[${i}]:4}
	local ${filter}=on
    done

    local transaction=/tmp/${TRANSACTION_FILE}.${REMOTE_USER}.gui.${$}
    rm -f ${transaction}

    for ((i=0;i<len;i++))
    do
	filter=${WAF_GENERIC_FILTER_ID[${i}]}
	echo waf rweb generic ${name} ${filter} $(eval echo \$${filter}) >> ${transaction}
    done

    execute-transaction ${transaction}
}

# Main

set-waf-rweb-generic
