#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-register-appliance()
{
    if test "${ATTRIBUTES[3]}" == "accept" ; then
	if test -z "${VALUES[2]}" ; then
	    gen-gui-error 2
	    return 0
	fi

	case "${VALUES[0]}" in
	    new)
		log-command "register" "appliance ${VALUES[0]} ${VALUES[1]} ..."
		execute-command "register appliance ${VALUES[0]} ${VALUES[1]} ${VALUES[2]}"
		;;
	    old)
		log-command "register" "appliance ${VALUES[0]} ..."
		execute-command "register appliance ${VALUES[0]} ${VALUES[2]}"
		;;
	    *)
		;;
	esac
    else
	gen-gui-error 5
    fi
}

set-register-license-key()
{
    if test "${ATTRIBUTES[2]}" == accept ; then
	if test "${VALUES[0]}" == register ; then

	    if test -z "${VALUES[1]}" ; then
		log-command register "license"
		execute-command "register license"
	    else
		log-command register "license ${VALUES[1]}"
		execute-command "register license ${VALUES[1]}"
	    fi
	else
	    log-command register clear
	    execute-command "register clear"
	fi
    else
	gen-gui-error 5
    fi
}

set-register()
{
    if test "${ATTRIBUTES[1]}" == os_key ; then
	set-register-license-key
    else
	set-register-appliance
    fi
}

set-register
