#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-authenticate()
{
    local i mode var

    local ldap=off
    local kerberos=off
    local web=off
    local rweb=off

    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}

    for ((i=1 ; i<${ATTRIBUTE_NB} ; i++))
    do
	mode=${ATTRIBUTES[${i}]}
	local ${mode}=on
    done

    echo authenticate mode ldap ${ldap}		 > ${transaction}
    echo authenticate mode kerberos ${kerberos}	>> ${transaction}
    echo authenticate web ${web}		>> ${transaction}
    echo authenticate rweb ${rweb}		>> ${transaction}

    execute-transaction ${transaction}
}

set-authenticate
