#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-admin-snmp-certificate()
{
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    test -n "${VALUES[0]}" || return 0

    case ${VALUES[0]} in
	raz)
	    echo "admin snmp certificate raz" >> ${transaction}
	    ;;
	load)
	    echo "admin snmp certificate load '${VALUES[1]:1}' '${VALUES[2]}' '${VALUES[3]}'" >> ${transaction}
	    ;;
	*)
	    ;;
    esac

    execute-transaction ${transaction}
}

set-admin-snmp-certificate
