#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-firewall-dos()
{
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    if test -n "${VALUES[0]}" ; then
	echo "firewall dos tcpflood set '${VALUES[0]} ${VALUES[1]}'" >> ${transaction}
    else
	echo "firewall dos tcpflood default" >> ${transaction}
    fi

    if test -n "${VALUES[2]}" ; then
	echo "firewall dos udpflood set '${VALUES[2]} ${VALUES[3]}'" >> ${transaction}
    else
	echo "firewall dos udpflood default" >> ${transaction}
    fi

    if test -n "${VALUES[4]}" ; then
	echo "firewall dos webflood set '${VALUES[4]} ${VALUES[5]}'" >> ${transaction}
    else
	echo "firewall dos webflood default" >> ${transaction}
    fi

    if test -n "${VALUES[6]}" ; then
	echo "firewall dos rwebflood set '${VALUES[6]} ${VALUES[7]}'" >> ${transaction}
    else
	echo "firewall dos rwebflood default" >> ${transaction}
    fi

    if test -n "${VALUES[8]}" ; then
	echo "firewall dos piptcp set '${VALUES[8]}'" >> ${transaction}
    else
	echo "firewall dos piptcp default" >> ${transaction}
    fi

    if test -n "${VALUES[9]}" ; then
	echo "firewall dos pipweb set '${VALUES[9]}'" >> ${transaction}
    else
	echo "firewall dos pipweb default" >> ${transaction}
    fi

    if test -n "${VALUES[10]}" ; then
	echo "firewall dos piprweb set '${VALUES[10]}'" >> ${transaction}
    else
	echo "firewall dos piprweb default" >> ${transaction}
    fi

    if test -n "${VALUES[11]}" ; then
	echo "firewall dos pipdns set '${VALUES[11]}'" >> ${transaction}
    else
	echo "firewall dos pipdns default" >> ${transaction}
    fi

    if test -n "${VALUES[12]}" ; then
	echo "firewall dos pipocsp set '${VALUES[12]}'" >> ${transaction}
    else
	echo "firewall dos pipocsp default" >> ${transaction}
    fi

    execute-transaction ${transaction}
}

set-firewall-dos
