#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-tls-server-manage()
{
    if test -n "${VALUES[5]}" ; then
	if test "${VALUES[1]}" == 'csr' -a "${VALUES[2]}" == 'load' -a -n "${VALUES[6]}" ; then
	    if test -z "${VALUES[7]}" ; then
		log-command "tls" "server ${VALUES[2]} ${VALUES[0]} ${VALUES[1]} ${VALUES[3]:1} ${VALUES[4]} ${VALUES[5]} ${VALUES[6]}"
		execute-command "tls server ${VALUES[2]} ${VALUES[0]} ${VALUES[1]} ${VALUES[3]:1} ${VALUES[4]} ${VALUES[5]} ${VALUES[6]}"
	    else
		log-command "tls" "server ${VALUES[2]} ${VALUES[0]} ${VALUES[1]} ${VALUES[3]:1} ${VALUES[4]} ${VALUES[5]} ${VALUES[6]} ocsp"
		execute-command "tls server ${VALUES[2]} ${VALUES[0]} ${VALUES[1]} ${VALUES[3]:1} ${VALUES[4]} ${VALUES[5]} ${VALUES[6]} ocsp"
	    fi
	else
	    log-command "tls" "server ${VALUES[2]} ${VALUES[0]} ${VALUES[1]} ${VALUES[3]:1} ${VALUES[4]} ${VALUES[5]}"
	    execute-command "tls server ${VALUES[2]} ${VALUES[0]} ${VALUES[1]} ${VALUES[3]:1} ${VALUES[4]} ${VALUES[5]}"
	fi
    else
	gen-gui-error 6
    fi
}

set-tls-server-manage
