#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-urllist()
{
    local pos=0 entry_pos name_pos del_pos 
    
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    while test ${pos} -lt ${ATTRIBUTE_NB}
    do
	entry_pos=${pos}
	name_pos=$[${pos} + 1]
	del_pos=$[${pos} + 2]
	
	[[ "${ATTRIBUTES[${del_pos}]}" =~ ^del_[0-9]+$ ]]
	if test ${?} -ne 0 ; then
	    if test "${VALUES[${entry_pos}]}" == anew -a -n "${VALUES[${name_pos}]}" ; then
		if test -n "${VALUES[${pos}]}" ; then
		    echo "urllist add '${VALUES[${name_pos}]}'" >> ${transaction}
		fi
	    fi
	    pos=$[${pos} + 2]
	else
	    echo "urllist del '${VALUES[${name_pos}]}'" >> ${transaction}
	    pos=$[${pos} + 3]
	fi  
    done
    
    execute-transaction ${transaction}
}

set-urllist
