#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-ldap-asswd()
{
    if test -n "${VALUES[0]}" -a -n "${VALUES[1]}" ; then
	if test "${VALUES[0]}" == "${VALUES[1]}" ; then
	    log-command "password" "snmp community ..."
	    execute-command "password snmp community ${VALUES[0]}"
	else
	    gen-gui-error 4
	fi
    else
	gen-gui-error 1
    fi

    if test -n "${VALUES[2]}" -a -n "${VALUES[3]}" ; then
	if test "${VALUES[2]}" == "${VALUES[3]}" ; then
	    log-command "password" "snmp privacy ..."
	    execute-command "password snmp privacy ${VALUES[2]}"
	else
	    gen-gui-error 4
	fi
    fi
}

set-ldap-asswd
