#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-system-patch()
{
    local key=${ATTRIBUTES[1]}
    local value=${VALUES[1]}

    if test "${key}" == aload -a "${value}" == on ; then
	if test "${ATTRIBUTES[2]}" = accept ; then
	    log-command "system" "patch ${key}"
	    execute-command "system patch ${key}"
	    return 0
	else
	    gen-gui-error 5
	    return 0
	fi
    fi

    if test "${ATTRIBUTES[4]}" != accept ; then
	gen-gui-error 5
	return 0
    fi

    if test -n "${VALUES[3]}" ; then
	log-command "system" "patch ${value:1} ${VALUES[2]} ${VALUES[3]}"
	execute-command "system patch ${value:1} ${VALUES[2]} ${VALUES[3]}"
    else
	gen-gui-error 6
    fi
}

set-system-patch
