#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-emails()
{
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    local ftp_email=${VALUES[0]}
    local admin_email=${VALUES[1]}
    local admin_name=${VALUES[2]}
    local server=${VALUES[3]}
    local port=${VALUES[4]}
    local username=${VALUES[5]}
    local password=${VALUES[6]}

    test "${server}" != auto || server=$(get-email-mx ${admin_email})

    if test -z "${ftp_email}" -o -z "${admin_email}" ; then
	gen-gui-error 23
	return 0
    fi

    test -n "${server}" || server=raz

    echo "email ftp '${ftp_email}'" >> ${transaction}
    echo "email admin '${admin_email}' '${admin_name}'" >> ${transaction}
    echo "email account '${server}' '${port}' '${username}' '${password}'" >> ${transaction}

    execute-transaction ${transaction}
}

set-emails
