#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-qos-borrow()
{
    local i borrow

    local internal_ingress=off
    local internal_egress=off
    local external_ingress=off
    local external_egress=off
    local auxiliary_ingress=off
    local auxiliary_egress=off

    for ((i=1 ; i<${ATTRIBUTE_NB} ; i++))
    do
	borrow=${ATTRIBUTES[${i}]}
	local ${borrow}=on
    done
    
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}

    echo qos borrow internal ingress ${internal_ingress}	 > ${transaction}
    echo qos borrow internal egress ${internal_egress}		>> ${transaction}
    echo qos borrow external ingress ${external_ingress}	>> ${transaction}
    echo qos borrow external egress ${external_egress}		>> ${transaction}
    echo qos borrow auxiliary ingress ${auxiliary_ingress}	>> ${transaction}
    echo qos borrow auxiliary egress ${auxiliary_egress}	>> ${transaction}

    execute-transaction ${transaction}
}

set-qos-borrow
