#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-waf-rweb-denyurl()
{
    local site_name=${VALUES[0]}
    local protocol=${VALUES[1]:1}
    local domainname_uri=${VALUES[2]}

    if test -z "${VALUES[2]}" ; then
	log-command "waf" "rweb denyurl raz ${site_name}"
	execute-command "waf rweb denyurl raz ${site_name}"
    else
	log-command "waf" "rweb denyurl set ${site_name} ${protocol}://${domainname_uri}"
	execute-command "waf rweb denyurl set ${site_name} ${protocol}://${domainname_uri}"
    fi
    GET_ARGS=${site_name}
}

# Main()

set-waf-rweb-denyurl
