#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-manager-gateway()
{
    local pos=0 entry_pos id_pos domain_pos ip_pos del_pos
    local id domain ip
    local del_issue

    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    while test ${pos} -lt ${ATTRIBUTE_NB}
    do
	entry_pos=${pos}
	id_pos=$[${pos} + 1]
	domain_pos=$[${pos} + 2]
	ip_pos=$[${pos} + 3]
	del_pos=$[${pos} + 4]

	id=${VALUES[${id_pos}]}

	[[ "${ATTRIBUTES[${del_pos}]}" =~ ^del_[0-9]+$ ]]
	if test ${?} -ne 0 ; then
	    domain=${VALUES[${domain_pos}]}
	    ip=${VALUES[${ip_pos}]}

	    if test "${VALUES[${entry_pos}]}" == anew -a \
		    -n "${id}" -a \
		    -n "${domain}" -a \
		    -n "${ip}" ; then
		echo "manager gateway add ${domain} ${id} ${ip}" >> ${transaction}
	    fi

	    pos=$[${pos} + 4]
	else
	    if gui-context-is-edited gateway ${id} ; then
		del_issue='yes'
	    else
		echo "manager gateway del ${id} force" >> ${transaction}
	    fi
	    pos=$[${pos} + 5]
	fi
    done

    if test -n "${del_issue}" ; then
	gen-gui-error 20
	rm -f ${transaction}
    else
	execute-transaction ${transaction}
    fi

    execute-transaction ${transaction}
}

# Main()

set-manager-gateway
