#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-qos-bw()
{
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}

    echo "qos bandwidth internal ingress '${VALUES[0]}'"   > ${transaction}
    echo "qos bandwidth internal egress '${VALUES[1]}'"   >> ${transaction}
    echo "qos bandwidth external ingress '${VALUES[2]}'"  >> ${transaction}
    echo "qos bandwidth external egress '${VALUES[3]}'"   >> ${transaction}
    echo "qos bandwidth auxiliary ingress '${VALUES[4]}'" >> ${transaction}
    echo "qos bandwidth auxiliary egress '${VALUES[5]}'"  >> ${transaction}

    execute-transaction ${transaction}
}

set-qos-bw
