#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-admin()
{
    local i mode

    local ssh=off
    local ssh_generate=off
    local ssh_password=off
    local wadmin=off
    local login_2fa=off
    local snmp=off
    local waudit=off

    for ((i=1 ; i<${ATTRIBUTE_NB} ; i++))
    do
	mode=${ATTRIBUTES[${i}]}
	local ${mode}=on
    done

    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}

    echo admin ssh ${ssh}			  > ${transaction}
    echo admin ssh generate ${ssh_generate}	 >> ${transaction}
    echo admin ssh password ${ssh_password}	 >> ${transaction}
    echo admin wadmin ${wadmin}			 >> ${transaction}
    echo admin snmp ${snmp}			 >> ${transaction}

    ! gui-contextual-is-allowed	  || echo admin waudit ${waudit} >> ${transaction}
    ! gui-is-in-top-level-context || echo admin 2fa ${login_2fa} >> ${transaction}

    execute-transaction ${transaction}
}

set-admin
