#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-guard-filter-ip()
{
    local pos=0 entry_pos del_pos
    local name_pos type_pos ip1_pos ip2_pos

    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    while test ${pos} -lt ${ATTRIBUTE_NB}
    do
	entry_pos=${pos}
	name_pos=$[${pos} + 1]
	type_pos=$[${pos} + 2]
	ip1_pos=$[${pos} + 3]
	ip2_pos=$[${pos} + 4]
	del_pos=$[${pos} + 5]
	
	if [[ "${ATTRIBUTES[${del_pos}]}" =~ ^del_[0-9]+$ ]] ; then
	    echo "guard filter ip del '${VALUES[${name_pos}]}'" >> ${transaction}
	    pos=$[${pos} + 6]
	else
	    if test "${VALUES[${entry_pos}]}" == anew -a \
		    -n "${VALUES[${name_pos}]}" -a \
		    -n "${VALUES[${type_pos}]}" -a \
		    -n "${VALUES[${ip1_pos}]}" ; then
		echo "guard filter ip add '${VALUES[${name_pos}]}' '${VALUES[${type_pos}]}' '${VALUES[${ip1_pos}]}' '${VALUES[${ip2_pos}]}'" >> ${transaction}
	    fi
	    pos=$[${pos} + 5]
	fi
    done
    
    execute-transaction ${transaction}
}

set-guard-filter-ip
