#!/bin/bash

###########################################################################
#
# MODULE:       GUI
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

set-qos-shape-gateway()
{
    local transaction=/tmp/${TRANSACTION_FILE}.wadmin.${REMOTE_USER}.${$}
    rm -f ${transaction}

    local flow_dev_gress flow_dev flow dev gress
    local i

    for ((i=0; i<ATTRIBUTE_NB ; i++))
    do
	flow_dev_gress=${ATTRIBUTES[${i}]}
	flow=${flow_dev_gress/_*}
	flow_dev=${flow_dev_gress%_*}
	dev=${flow_dev/*_}
	gress=${flow_dev_gress/*_}
	case ${flow} in
	    file|peer|default|web|tweb|rweb|antivirus|vpnipsec)
		case ${dev} in
		    internal|external|auxiliary)
			case ${gress} in
			    ingress|egress)
				echo "qos shape '${flow}' '${dev}' '${gress}' '${VALUES[${i}]}'" >> ${transaction}
				;;
			    *)
				;;
			esac
			;;
		    *)
			;;
		esac
		;;
	    *)
		;;
	esac
    done

    execute-transaction ${transaction}
}

set-qos-shape-gateway
