#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

__complete-dns()
{
    test -n "${COMP_CWORD-1}" || return 1

    case ${COMP_CWORD} in
	1)
	    case ${COMP_WORDS[1]} in
		a|ad|add)
		    COMPREPLY=(add)
		    ;;
		d|de|del)
		    COMPREPLY=(del)
		    ;;
		r)
		    COMPREPLY=('' raz resolve)
		    ;;
		ra|raz)
		    COMPREPLY=(raz)
		    ;;
		re|res|reso|resol|resolv|resolve)
		    COMPREPLY=(resolve)
		    ;;
		'')
		    COMPREPLY=('' '<RET>' add del raz resolve)
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	2)
	    case ${COMP_WORDS[1]} in
		resolve)
		    case ${COMP_WORDS[2]} in
			o)
			    COMPREPLY=('' on off)
			    ;;
			of|off)
			    COMPREPLY=(off)
			    ;;
			on)
			    COMPREPLY=(on)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' on off)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		add|del)
		    case ${COMP_WORDS[2]} in
			l|lo|loc|loca|local|localh|localho|localhos|localhost)
			    COMPREPLY=(localhost)
			    ;;
			'')
			    COMPREPLY=('' '<ip>' localhost)
			    ;;
			*)
			    COMPREPLY=('' '<ip>')
			    ;;
		    esac
		    ;;
		raz)
		    COMPREPLY=()
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	*)
	    COMPREPLY=()
	    ;;
    esac
}
