#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

__complete-email()
{
    test -n "${COMP_CWORD-1}" || return 1

    case ${COMP_CWORD} in
	1)
	    case ${COMP_WORDS[1]} in
		a)
		    COMPREPLY=('' '<RET>' account admin)
		    ;;
		ac|acc|acco|accou|accoun|account)
		    COMPREPLY=(account)
		    ;;
		ad|adm|admi|admin)
		    COMPREPLY=(admin)
		    ;;
		f|ft|ftp)
		    COMPREPLY=(ftp)
		    ;;
		s|se|sen|send)
		    COMPREPLY=('send')
		    ;;
		'')
		    COMPREPLY=('' '<RET>' account admin ftp send)
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	2)
	    case ${COMP_WORDS[1]} in
		admin|ftp)
		    COMPREPLY=('' '<RET>' '<email-address>')
		    ;;
		account)
		    COMPREPLY=('' '<RET>' '<server>' auto raz)
		    ;;
		send)
		    COMPREPLY=('' '<email-address>')
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	3)
	    case ${COMP_WORDS[1]} in
		account)
		    COMPREPLY=('' '<port>')
		    ;;
		admin)
		    COMPREPLY=('' '<RET>' '<name>')
		    ;;
		send)
		    COMPREPLY=('' '<RET>' '<name>')
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	4)
	    case ${COMP_WORDS[1]} in
		account)
		    COMPREPLY=('' '<username>')
		    ;;
		send)
		    COMPREPLY=('' '<RET>' '<subject>')
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	5)
	    case ${COMP_WORDS[1]} in
		account)
		    COMPREPLY=('' '<RET>' '<password>')
		    ;;
		send)
		    COMPREPLY=('' '<RET>' '<message>')
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	*)
	    COMPREPLY=()
	    ;;
    esac
}
