#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

__complete-embedded()
{
    test -n "${COMP_CWORD-1}" || return 1

    case ${COMP_CWORD} in
	1)
	    case ${COMP_WORDS[1]} in
		b|be|bev|bevy|bevyp|bevypn)
		    COMPREPLY=(bevypn)
		    ;;
		'')
		    COMPREPLY=('' '<RET>' bevypn)
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	2)
	    case ${COMP_WORDS[1]} in
		bevypn)
		    case ${COMP_WORDS[2]} in
			o)
			    COMPREPLY=('' on off)
			    ;;
			of|off)
			    COMPREPLY=(off)
			    ;;
			on)
			    COMPREPLY=(on)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' on off)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	3)
	    case ${COMP_WORDS[1]} in
		bevypn)
		    case ${COMP_WORDS[2]} in
			on)
			    COMPREPLY=('' '<site-name>')
			    ;;
			off)
			    COMPREPLY=('' '<RET>' '<site-name>')
			    ;;

			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	4)
	    case ${COMP_WORDS[1]} in
		bevypn)
		    case ${COMP_WORDS[2]} in
			on)
			    COMPREPLY=('' '<tls-id>[:<ca-id>]')
			    ;;
			off)
			    COMPREPLY=('' '<RET>' '<tls-id>[:<ca-id>]')
			    ;;

			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac

	    ;;
    esac
}
