#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

__complete-manager()
{
    test -n "${COMP_CWORD-1}" || return 1
    
    case ${COMP_CWORD} in
	1)
	    case ${COMP_WORDS[1]} in
		g|ga|gat|gate|gatew|gatewa|gateway)
		    COMPREPLY=(gateway)
		    ;;
		s)
		    COMPREPLY=('' ssh sync)
		    ;;
		sy|syn|sync)
		    COMPREPLY=(sync)
		    ;;
		ss|ssh)
		    COMPREPLY=(ssh)
		    ;;
		t|te|tem|temp|templ|templa|templat|template)
		    COMPREPLY=(template)
		    ;;
		'')
		    COMPREPLY=('' gateway sync ssh template)
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	2)
	    case ${COMP_WORDS[1]} in
		gateway)
		    case ${COMP_WORDS[2]} in
			a|ad|add)
			    COMPREPLY=(add)
			    ;;
			b|be|beg|begi|begin)
			    COMPREPLY=(begin)
			    ;;
			d|de|del)
			    COMPREPLY=(del)
			    ;;
			p|pu)
			    COMPREPLY=('' pull push)
			    ;;
			pus|push)
			    COMPREPLY=(push)
			    ;;
			pul|pull)
			    COMPREPLY=(pull)
			    ;;
			r)
			    COMPREPLY=('' raz report)
			    ;;
			ra|raz)
			    COMPREPLY=(raz)
			    ;;
			re|rep|repo|repor|report)
			    COMPREPLY=(report)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' add begin del pull push raz report)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		sync)
		    case ${COMP_WORDS[2]} in
			p|pe|pee|peer)
			    COMPREPLY=(peer)
			    ;;
			r)
			    COMPREPLY=('' report role)
			    ;;
			ro|rol|role)
			    COMPREPLY=(role)
			    ;;
			re|rep|repo|repor|report)
			    COMPREPLY=(report)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' peer report role)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		template)
		    case ${COMP_WORDS[2]} in
			a|ad|add)
			    COMPREPLY=(add)
			    ;;
			b|be|beg|begi|begin)
			    COMPREPLY=(begin)
			    ;;
			d|de|del)
			    COMPREPLY=(del)
			    ;;
			r)
			    COMPREPLY=(''raz report)
			    ;;
			ra|raz)
			    COMPREPLY=(raz)
			    ;;
			re|rep|repo|repor|report)
			    COMPREPLY=(report)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' add begin del raz report)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		ssh)
		    case ${COMP_WORDS[2]} in
			f|'fi'|fin|fing|finge|finger|fingerp|fingerpr|fingerpri|fingerprin|fingerprint)
			    COMPREPLY=(fingerprint)
			    ;;
			g|ge|gen|gene|gener|genera|generat|generate)
			    COMPREPLY=(generate)
			    ;;
			p)
			    COMPREPLY=('' private public)
			    ;;
			pr|pri|priv|priva|privat|private)
			    COMPREPLY=(private)
			    ;;
			pu|pub|publ|publi|public)
			    COMPREPLY=(public)
			    ;;
			s|sh|sho|show)
			    COMPREPLY=(show)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' fingerprint generate private public show)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	3)
	    case ${COMP_WORDS[1]} in
		gateway)
		    case ${COMP_WORDS[2]} in
			add)
			    COMPREPLY=('' '<domain-id>')
			    ;;
			del)
			    COMPREPLY=('' '<gateway-id>')
			    ;;

			begin)
			    case ${COMP_WORDS[3]} in
			    	c|co|con|conf)
				    COMPREPLY=(conf)
				    ;;
				e|ex|exe|'exec')
				    COMPREPLY=('exec')
				    ;;				    
				'')
				    COMPREPLY=('' conf exec)
				    ;;
				*)
				    ;;
			    esac				
			    ;;
			pull|push)
			    COMPREPLY=('' '<RET>' '<domain-id>')
			    ;;
			raz)
			    case ${COMP_WORDS[3]} in
			    	f|fo|'for'|forc|force)
				    COMPREPLY=(force)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' force)
				    ;;
				*)
				    ;;
			    esac				
			    ;;
			report)
			    case ${COMP_WORDS[3]} in
				e|ex|exe|'exec')
				    COMPREPLY=('exec')
				    ;;
				p|pu)
				    COMPREPLY=('' pull push)
				    ;;
				pus|push)
				    COMPREPLY=(push)
				    ;;
				pul|pull)
				    COMPREPLY=(pull)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' exec pull push)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			'')
			    COMPREPLY=('' '<RET>' add begin del pull push raz report)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		ssh)
		    case ${COMP_WORDS[2]} in
			private|public)
			    case ${COMP_WORDS[3]} in
				l|lo|loa|load)
				    COMPREPLY=(load)
				    ;;
				s|sa|sav|save)
				    COMPREPLY=(save)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' load save)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		sync)
		    case ${COMP_WORDS[2]} in
			peer)
			    COMPREPLY=('' '<peer-manager-ip>')
			    ;;
			role)
			    case ${COMP_WORDS[3]} in
				a|al|alo|alon|alone)
				    COMPREPLY=(alone)
				    ;;
				m|ma|mas|mast|maste|master)
				    COMPREPLY=(master)
				    ;;
				s|sl|sla|slav|slave)
				    COMPREPLY=(slave)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' alone master slave)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		template)
		    case ${COMP_WORDS[2]} in
			add|del)
			    COMPREPLY=('' '<template-name>')
			    ;;
			raz)
			    case ${COMP_WORDS[3]} in
			    	f|fo|'for'|forc|force)
				    COMPREPLY=(force)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' force)
				    ;;
				*)
				    ;;
			    esac				
			    ;;
			begin)
			    case ${COMP_WORDS[3]} in
			    	c|co|con|conf)
				    COMPREPLY=(conf)
				    ;;
				e|ex|exe|'exec')
				    COMPREPLY=('exec')
				    ;;				    
				'')
				    COMPREPLY=('' conf exec)
				    ;;
				*)
				    ;;
			    esac				
			    ;;
			report)
			    case ${COMP_WORDS[3]} in
				e|ex|exe|'exec')
				    COMPREPLY=('exec')
				    ;;
				'')
				    COMPREPLY=('' exec)
				    ;;
				*)
				    OMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	4)
	    case ${COMP_WORDS[1]} in
		sync)
		    case ${COMP_WORDS[2]} in
			peer)
			    COMPREPLY=('' '<RET>' "'<peer-manager-public-ssh-key>'")
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		gateway)
		    case ${COMP_WORDS[2]} in
			add)
			    COMPREPLY=('' '<gateway-id>')
			    ;;
			del)
			    case ${COMP_WORDS[4]} in
				f|fo|'for'|forc|force)
				    COMPREPLY=(force)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' force)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac				
			    ;;
			begin)
			    case ${COMP_WORDS[3]} in
				conf)
				    COMPREPLY=('' '<gateway-id>')
				    ;;
				'exec')
				    case ${COMP_WORDS[4]} in
					l|lo|loc|loca|local)
					    COMPREPLY=(local)
					    ;;
					r|re|rem|remo|remot|remote)
					    COMPREPLY=(remote)
					    ;;
					'')
					    COMPREPLY=('' local remote)
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			pull|push)
			    COMPREPLY=('' '<RET>' '<gateway-id>')
			    ;;
			report)
			    case ${COMP_WORDS[3]} in
				'exec')
				    case ${COMP_WORDS[4]} in
					l|lo|loc|loca|local)
					    COMPREPLY=(local)
					    ;;
					r|re|rem|remo|remot|remote)
					    COMPREPLY=(remote)
					    ;;
					'')
					    COMPREPLY=('' local remote)
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			'')
			    COMPREPLY=('' '<RET>' add begin del pull push raz report)
			    ;;

			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		ssh)
		    case ${COMP_WORDS[2]} in
			private|public)
			    case ${COMP_WORDS[3]} in
				load|save)
				    case ${COMP_WORDS[4]} in
					f|ft|ftp)
					    COMPREPLY=(ftp)
					    ;;
					s|sf|sft|sftp)
					    COMPREPLY=(sftp)
					    ;;
					t|tf|tft|tftp)
					    COMPREPLY=(tftp)
					    ;;
					'')
					    COMPREPLY=('' ftp sftp tftp)
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		template)
		    case ${COMP_WORDS[2]} in
			add)
			    case ${COMP_WORDS[4]} in
				g|ga|gat|gate|gatew|gatewa|gateway)
				    COMPREPLY=(gateway)
				    ;;
				t|te|tem|temp|templ|templa|templat|template)
				    COMPREPLY=(template)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' gateway template)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			del)
			    case ${COMP_WORDS[4]} in
				f|fo|'for'|forc|force)
				    COMPREPLY=(force)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' force)
				    ;;
				*)
				    ;;
			    esac				
			    ;;
			begin)
			    case ${COMP_WORDS[3]} in
				conf)
				    COMPREPLY=('' '<template-name>')
				    ;;
				'exec')
				    COMPREPLY=('' '<RET>' '<template-name>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;

			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	5)
	    case ${COMP_WORDS[1]} in
		ssh)
		    case ${COMP_WORDS[2]} in
			private|public)
			    case ${COMP_WORDS[3]} in
				load|save)
				    case ${COMP_WORDS[4]} in
					ftp|sftp|tftp)
					    COMPREPLY=('' '<file-server>')
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		template)
		    case ${COMP_WORDS[2]} in
			add)
			    case ${COMP_WORDS[4]} in
				template|gateway)
				    COMPREPLY=('' '<source-id>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		gateway)
		    case ${COMP_WORDS[2]} in
			add)
			    COMPREPLY=('' '<gateway-ip>')
			    ;;
			begin)
			    case ${COMP_WORDS[3]} in
				'exec')
				    case ${COMP_WORDS[4]} in
					local|remote)
					    COMPREPLY=('' '<RET>' '<domain-id>')
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	6)
	    case ${COMP_WORDS[1]} in
		gateway)
		    case ${COMP_WORDS[2]} in
			begin)
			    case ${COMP_WORDS[3]} in
				'exec')
				    case ${COMP_WORDS[4]} in
					local|remote)
					    COMPREPLY=('' '<RET>' '<gateway-id>')
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		ssh)
		    case ${COMP_WORDS[2]} in
			private|public)
			    case ${COMP_WORDS[3]} in
				load|save)
				    case ${COMP_WORDS[4]} in
					ftp|sftp|tftp)
					    COMPREPLY=('' '<file-path>')
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	*)
	    COMPREPLY=()
	    ;;
    esac
}
