#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

__complete-password()
{
    test -n "${COMP_CWORD-1}" || return 1

    case ${COMP_CWORD} in
	1)
	    case ${COMP_WORDS[1]} in
		c|co|con|cons|conso|consol|console)
		    COMPREPLY=(console)
		    ;;
		e|em|ema|emai|email)
		    COMPREPLY=(email)
		    ;;
		f|'fi'|fil|file)
		    COMPREPLY=(file)
		    ;;
		k|ke|ker|kerb|kerbe|kerber|kerbero|kerberos)
		    COMPREPLY=(kerberos)
		    ;;
		l)
		    COMPREPLY=('' '<RET>' ldap login)
		    ;;
		ld|lda|ldap)
		    COMPREPLY=(ldap)
		    ;;
		lo|log|logi|login)
		    COMPREPLY=(login)
		    ;;
		s|sn|snm|snmp)
		    COMPREPLY=(snmp)
		    ;;
		w|wa|wad|wadm|wadmi|wadmin)
		    COMPREPLY=(wadmin)
		    ;;
		'')
		    COMPREPLY=('' '<RET>' console email file kerberos ldap login snmp wadmin)
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	2)
	    case ${COMP_WORDS[1]} in
		login|wadmin)
		    COMPREPLY=('' '<RET>' '<current-password>')
		    ;;
		kerberos)
		    COMPREPLY=('' '<RET>' '<shared-password>')
		    ;;
		email|ldap)
		    COMPREPLY=('' '<RET>' '<password>')
		    ;;
		file)
		    case ${COMP_WORDS[2]} in
			a|ad|add)
			    COMPREPLY=(add)
			    ;;
			d|de|del)
			    COMPREPLY=(del)
			    ;;
			r|ra|raz)
			    COMPREPLY=(raz)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' add del raz)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		snmp)
		    case ${COMP_WORDS[2]} in
			c|co|com|comm|commu|commun|communi|communit|community)
			    COMPREPLY=(community)
			    ;;
			p|pr|pri|priv|priva|privac|privacy)
			    COMPREPLY=(privacy)
			    ;;
			'')
			    COMPREPLY=('' community privacy)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	3)
	    case ${COMP_WORDS[1]} in
		login|wadmin)
		    COMPREPLY=('' '<RET>' '<new-password>')
		    ;;
		file)
		    case ${COMP_WORDS[2]} in
			add|del)
			    case ${COMP_WORDS[3]} in
				f|ft|ftp)
				    COMPREPLY=(ftp)
				    ;;
				s|sf|sft|sftp)
				    COMPREPLY=(sftp)
				    ;;
				'')
				    COMPREPLY=('' ftp sftp)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		snmp)
		    case ${COMP_WORDS[2]} in
			community)
			    COMPREPLY=('' '<RET>' '<community-string>')
			    ;;
			privacy)
			    COMPREPLY=('' '<RET>' '<privacy-password>')
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	4)
	    case ${COMP_WORDS[1]} in
		file)
		    case ${COMP_WORDS[2]} in
			add|del)
			    case ${COMP_WORDS[3]} in
				ftp|sftp)
				    COMPREPLY=('' '<file-server>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	5)
	    case ${COMP_WORDS[1]} in
		file)
		    case ${COMP_WORDS[2]} in
			add)
			    case ${COMP_WORDS[3]} in
				ftp|sftp)
				    COMPREPLY=('' '<login>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	6)
	    case ${COMP_WORDS[1]} in
		file)
		    case ${COMP_WORDS[2]} in
			add)
			    case ${COMP_WORDS[3]} in
				ftp|sftp)
				    COMPREPLY=('' '<RET>' '<password>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;	
	*)
	    ;;
    esac
}
