#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

__complete-peer()
{
    test -n "${COMP_CWORD-1}" || return 1

    case ${COMP_CWORD} in
	1)
	    case ${COMP_WORDS[1]} in
		s|sh|sha|shar|share)
		    COMPREPLY=(share)
		    ;;
		n|ne|nex|next)
		    COMPREPLY=(next)
		    ;;
		h|ha)
		    COMPREPLY=(ha)
		    ;;
		p|pr|pre|prev|previ|previo|previou|previous)
		    COMPREPLY=(previous)
		    ;;
		'')
		    COMPREPLY=('' '<RET>' share ha next previous)
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	2)
	    case ${COMP_WORDS[1]} in
		share|ha|next|previous)
		    case ${COMP_WORDS[2]} in
			a|ad|add)
			    COMPREPLY=(add)
			    ;;
			d|de|del)
			    COMPREPLY=(del)
			    ;;
			r|ra|raz)
			    COMPREPLY=(raz)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' add del raz)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	3)
	    case ${COMP_WORDS[1]} in
		share|ha|next|previous)
		    case ${COMP_WORDS[2]} in
			add|del)
			    COMPREPLY=('' '<ip>')
			    ;;
			raz)
			    COMPREPLY=()
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	4)
	    case ${COMP_WORDS[1]} in
		share|ha|previous)
		    case ${COMP_WORDS[2]} in
			add)
			    COMPREPLY=('' '<RET>' '<qos>')
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		next)
		    case ${COMP_WORDS[2]} in
			add)
			    COMPREPLY=('' '<RET>' '<port-number>')
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	*)
	    COMPREPLY=()
	    ;;
    esac
}
