#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

__complete-transparent()
{
    test -n "${COMP_CWORD-1}" || return 1

    case ${COMP_CWORD} in
	1)
	    case ${COMP_WORDS[1]} in
		r|ra|raz)
		    COMPREPLY=(raz)
		    ;;
		a|ad|add)
		    COMPREPLY=(add)
		    ;;
		d|de|del)
		    COMPREPLY=(del)
		    ;;
		'')
		    COMPREPLY=('' '<RET>' raz add del)
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	2)
	    case ${COMP_WORDS[1]} in
		add|del)
		    case ${COMP_WORDS[2]} in
			i|'in'|int|inte|inter|intern|interna|internal)
			    COMPREPLY=(internal)
			    ;;
			a|au|aux|auxi|auxil|auxili|auxilia|auxiliar|auxiliary)
			    COMPREPLY=(auxiliary)
			    ;;
			v|vp|vpn|vpni|vpnip|vpnips|vpnipse|vpnipsec)
			    COMPREPLY=(vpnipsec)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' internal auxiliary vpnipsec)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	3)
	    case ${COMP_WORDS[1]} in
		add|del)
		    case ${COMP_WORDS[2]} in
			internal|auxiliary|vpnipsec)
			    COMPREPLY=('' '<network-ip>')
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	4)
	    case ${COMP_WORDS[1]} in
		add|del)
		    case ${COMP_WORDS[2]} in
			internal|auxiliary|vpnipsec)
			    COMPREPLY=('' '<RET>' '<network-mask>')
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	5)
	    case ${COMP_WORDS[1]} in
		add)
		    case ${COMP_WORDS[2]} in
			internal|auxiliary|vpnipsec)
			    COMPREPLY=('' '<RET>' '<qos>')
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	*)
	    COMPREPLY=()
	    ;;
    esac
}
