#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

__complete-waf()
{
    test -n "${COMP_CWORD-1}" || return 1

    case ${COMP_CWORD} in
	1)
	    case ${COMP_WORDS[1]} in
		b|by|byp|bypa|bypas|bypass)
		    COMPREPLY=(bypass)
		    ;;
		d|'do'|dos)
		    COMPREPLY=(dos)
		    ;;
		e|er|err|erro|error|errors)
		    COMPREPLY=(errors)
		    ;;
		i|im|ime|imet|imeth|imetho|imethod|imethods)
		    COMPREPLY=(imethods)
		    ;;		    
		g|ge|gen|gene|gener|generi|generic)
		    COMPREPLY=(generic)
		    ;;
		l)
		    COMPREPLY=('' level limit)
		    ;;
		le|lev|leve|level)
		    COMPREPLY=(level)
		    ;;
		li|lim|limi|limit)
		    COMPREPLY=(limit)
		    ;;
		r)
		    COMPREPLY=('' reputation rweb)
		    ;;
		rw|rwe|rweb)
		    COMPREPLY=(rweb)
		    ;;
		re|rep|repu|reput|reputa|reputat|reputati|reputatio|reputation)
		    COMPREPLY=(reputation)
		    ;;
		s|sc|sco|scor|score)
		    COMPREPLY=(score)
		    ;;
		'')
		    COMPREPLY=('' bypass dos errors imethods generic limit level reputation rweb score)
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	2)
	    case ${COMP_WORDS[1]} in
		bypass)
		    case ${COMP_WORDS[2]} in
			a|ap|app|appl|appli|applic|applica|applicat|applicati|applicatio|application)
			    COMPREPLY=(application)
			    ;;
			r|ru|rul|rule)
			    COMPREPLY=(rule)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' application rule)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		dos)
		    COMPREPLY=('' '<RET>' '<requests-limit>')
		    ;;
		errors|imethods)
		    case ${COMP_WORDS[2]} in
			a|al|all|allo|allow)
			    COMPREPLY=(allow)
			    ;;
			d|de|den|deny)
			    COMPREPLY=(deny)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' allow deny)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		generic)
		    case ${COMP_WORDS[2]} in
			d|dl)
			    COMPREPLY=('' dliis dljava dlphp dlsql)
			    ;;
			dli|dlii|dliis)
			    COMPREPLY=(dliis)
			    ;;
			dlj|dlja|dljav|dljava)
			    COMPREPLY=()
			    ;;
			dlp|dlph|dlphp)
			    COMPREPLY=(dlphp)
			    ;;
			dls|dlsq|dlsql)
			    COMPREPLY=(dlsql)
			    ;;
			j|ja|jav|java)
			    COMPREPLY=(java)
			    ;;
			l|lf|lfi)
			    COMPREPLY=(lfi)
			    ;;
			n|no|nod|node|nodej|nodejs)
			    COMPREPLY=(nodejs)
			    ;;
			r)
			    COMPREPLY=('' rce rfi)
			    ;;
			rc|rce)
			    COMPREPLY=(rce)
			    ;;
			rf|rfi)
			    COMPREPLY=(rfi)
			    ;;
			s)
			    COMPREPLY=('' sf sqli)
			    ;;
			sf)
			    COMPREPLY=(sf)
			    ;;
			sq|sql|sqli)
			    COMPREPLY=(sqli)
			    ;;
			x|xs|xss)
			    COMPREPLY=(xss)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' dliis dljava dlphp dlsql java lfi nodejs php rce rfi sf sqli xss)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		level)
		    COMPREPLY=('' '<RET>' '<level-nb>')
		    ;;
		limit)
		    case ${COMP_WORDS[2]} in
			r|re)
			    COMPREPLY=('' response request)
			    ;;
			res|resp|respo|respon|respons|response)
			    COMPREPLY=(response)
			    ;;
			req|requ|reque|reques|request)
			    COMPREPLY=(request)
			    ;;
			a)
			    COMPREPLY=('' assertions arguments)
			    ;;
			as|ass|asse|asser|assert|asserti|assertio|assertion|assertions)
			    COMPREPLY=(assertions)
			    ;;
			ar|arg|argu|argum|argume|argumen|argument|arguments)
			    COMPREPLY=(arguments)
			    ;;
			n|na|nam|name)
			    COMPREPLY=(name)
			    ;;
			v|va|val|valu|value)
			    COMPREPLY=(value)
			    ;;
			f|"fi"|fil|file|files)
			    COMPREPLY=(files)
			    ;;
			'')
			    COMPREPLY=('' '<RET>' response request assertions name value arguments files)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		reputation)
		    case ${COMP_WORDS[2]} in
			c|co|cou|coun|count|countr|country)
			    COMPREPLY=(country)
			    ;;
			r|rb|rbl)
			    COMPREPLY=(rbl)
			    ;;

			'')
			    COMPREPLY=('' '<RET>' country rbl)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		rweb)
		    case ${COMP_WORDS[2]} in
			b|by|byp|bypa|bypas|bypass)
			    COMPREPLY=(bypass)
			    ;;
			g|ge|gen|gene|gener|generi|generic)
			    COMPREPLY=(generic)
			    ;;
			c|cu|cus|cust|custo|custom)
			    COMPREPLY=(custom)
			    ;;
			a|au|aud|audi|audit)
			    COMPREPLY=(audit)
			    ;;
			d|de|den|deny|denyu|denyur|denyurl)
			    COMPREPLY=(denyurl)
			    ;;
			e|er|err|erro|error|errors)
			    COMPREPLY=(errors)
			    ;;
			'')
			    COMPREPLY=('' bypass errors generic custom audit denyurl)
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		score)
		    case ${COMP_WORDS[2]} in
			r|re)
			    COMPREPLY=('' response request)
			    ;;
			res|resp|respo|respon|respons|response)
			    COMPREPLY=(response)
			    ;;
			req|requ|reque|reques|request)
			    COMPREPLY=(request)
			    ;;
			*)
			    COMPREPLY=('' '<RET>' response request)
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	3)
	    case ${COMP_WORDS[1]} in
		bypass)
		    case ${COMP_WORDS[2]} in
			application|rule)
			    case ${COMP_WORDS[3]} in
				r|ra|raz)
				    COMPREPLY=(raz)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' raz)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		dos)
		    COMPREPLY=('' '<duration-period>')
		    ;;
		generic)
		    case ${COMP_WORDS[2]} in
			dliis|dljava|dlphp|dlsql|java|lfi|nodejs|php|rce|rfi|sf|sqli|xss)
			    case ${COMP_WORDS[3]} in
				o)
				    COMPREPLY=('' on off)
				    ;;
				of|off)
				    COMPREPLY=(off)
				    ;;
				on)
				    COMPREPLY=(on)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' on off)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		score)
		    case ${COMP_WORDS[2]} in
			response|request)
			    COMPREPLY=('' '<RET>' '<score-nb>')
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;

		limit)
		    case ${COMP_WORDS[2]} in
			response|request|files)
			    COMPREPLY=('' '<RET>' '<kilobyte-size>')
			    ;;
			assertions)
			    COMPREPLY=('' '<RET>' '<number>')
			    ;;
			name|value|arguments)
			    COMPREPLY=('' '<RET>' '<length>')
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		reputation)
		    case ${COMP_WORDS[2]} in
			rbl)
			    case ${COMP_WORDS[3]} in
				s|se|set)
				    COMPREPLY=(set)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' set)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			country)
			    case ${COMP_WORDS[3]} in
				a|ad|add)
				    COMPREPLY=(add)
				    ;;
				d|de|del)
				    COMPREPLY=(del)
				    ;;
				r|ra|raz)
				    COMPREPLY=(raz)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' add del raz)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		rweb)
		    case ${COMP_WORDS[2]} in
			audit|custom|generic)
			    COMPREPLY=('' '<RET>' '<site-name>')
			    ;;
			bypass)
			    case ${COMP_WORDS[3]} in
				a|ap|app|appl|appli|applic|applica|applicat|applicati|applicatio|application)
				    COMPREPLY=(application)
				    ;;
				r|ru|rul|rule)
				    COMPREPLY=(rule)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' application rule)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			errors)
			    case ${COMP_WORDS[3]} in
				r|ra|raz)
				    COMPREPLY=(raz)
				    ;;
				a|ad|add)
				    COMPREPLY=(add)
				    ;;
				d|de|del)
				    COMPREPLY=(del)
				    ;;
				s|sh|sho|show)
				    COMPREPLY=(show)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' raz add del show)
				    ;;
			    esac
			    ;;
			denyurl)
			    case ${COMP_WORDS[3]} in
				s|se|"set")
				    COMPREPLY=(set)
				    ;;
				r|ra|raz)
				    COMPREPLY=(raz)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' set raz)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	4)
	    case ${COMP_WORDS[1]} in
		dos)
		    COMPREPLY=('' '<blocking-period>')
		    ;;
		reputation)
		    case ${COMP_WORDS[2]} in
			country)
			    case ${COMP_WORDS[3]} in
				add|del)
				    COMPREPLY=('' '<country-code>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			rbl)
			    case ${COMP_WORDS[3]} in
				set)
				    COMPREPLY=('' '<RET>' '<api-key>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		rweb)
		    case ${COMP_WORDS[2]} in
			generic)
			    case ${COMP_WORDS[4]} in
				d|dl)
				    COMPREPLY=('' dliis dljava dlphp dlsql)
				    ;;
				dli|dlii|dliis)
				    COMPREPLY=(dliis)
				    ;;
				dlj|dlja|dljav|dljava)
				    COMPREPLY=()
				    ;;
				dlp|dlph|dlphp)
				    COMPREPLY=(dlphp)
				    ;;
				dls|dlsq|dlsql)
				    COMPREPLY=(dlsql)
				    ;;
				j|ja|jav|java)
				    COMPREPLY=(java)
				    ;;
				l|lf|lfi)
				    COMPREPLY=(lfi)
				    ;;
				n|no|nod|node|nodej|nodejs)
				    COMPREPLY=(nodejs)
				    ;;
				r)
				    COMPREPLY=('' rce rfi)
				    ;;
				rc|rce)
				    COMPREPLY=(rce)
				    ;;
				rf|rfi)
				    COMPREPLY=(rfi)
				    ;;
				s)
				    COMPREPLY=('' sf sqli)
				    ;;
				sf)
				    COMPREPLY=(sf)
				    ;;
				sq|sql|sqli)
				    COMPREPLY=(sqli)
				    ;;
				x|xs|xss)
				    COMPREPLY=(xss)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' dliis dljava dlphp dlsql java lfi nodejs php rce rfi sf sqli xss)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			bypass)
			    case ${COMP_WORDS[3]} in
				application|rule)
				    COMPREPLY=('' '<RET>' '<site-name>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			custom)
			    case ${COMP_WORDS[4]} in
				l|lo|loa|load)
				    COMPREPLY=(load)
				    ;;
				s|sa|sav|save)
				    COMPREPLY=(save)
				    ;;
				c|cl|cle|clea|clear)
				    COMPREPLY=(clear)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' load save clear)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			audit)
			    case ${COMP_WORDS[4]} in
				o)
				    COMPREPLY=('' on off)
				    ;;
				of|off)
				    COMPREPLY=(off)
				    ;;
				on)
				    COMPREPLY=(on)
				    ;;
				'')
				    COMPREPLY=('' '<RET>' on off)
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			errors)
			    case ${COMP_WORDS[3]} in
				add|del|show)
				    COMPREPLY=('' '<RET>' '<site-name>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			denyurl)
			    case ${COMP_WORDS[3]} in
				set)
				    COMPREPLY=('' '<site-name>')
				    ;;
				raz)
				    COMPREPLY=('' '<RET>' '<site-name>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	5)
	    case ${COMP_WORDS[1]} in
		rweb)
		    case ${COMP_WORDS[2]} in
			generic)
			    case ${COMP_WORDS[4]} in
				dliis|dljava|dlphp|dlsql|java|lfi|nodejs|php|rce|rfi|sf|sqli|xss)
				    case ${COMP_WORDS[5]} in
					o)
					    COMPREPLY=('' on off)
					    ;;
					of|off)
					    COMPREPLY=(off)
					    ;;
					on)
					    COMPREPLY=(on)
					    ;;
					'')
					    COMPREPLY=('' '<RET>' on off)
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			bypass)
			    case ${COMP_WORDS[3]} in
				application)
				    case ${COMP_WORDS[5]} in
					r|ra|raz)
					    COMPREPLY=(raz)
					    ;;
					s|se|set)
					    COMPREPLY=(set)
					    ;;
					'')
					    COMPREPLY=('' '<RET>' set raz)
					    ;;
				    esac
				    ;;

				rule)
				    case ${COMP_WORDS[5]} in
					r|ra|raz)
					    COMPREPLY=(raz)
					    ;;
					a|ad|add)
					    COMPREPLY=(add)
					    ;;
					d|de|del)
					    COMPREPLY=(del)
					    ;;
					'')
					    COMPREPLY=('' '<RET>' raz add del)
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			errors)
			    case ${COMP_WORDS[3]} in
				add)
				    case ${COMP_WORDS[5]} in
					a|al|all|allo|allow)
					    COMPREPLY=(allow)
					    ;;
					d|de|den|deny)
					    COMPREPLY=(deny)
					    ;;
					'')
					    COMPREPLY=('' '<RET>' allow deny)
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			custom)
			    case ${COMP_WORDS[4]} in
				load|save)
				    case ${COMP_WORDS[5]} in
					f|ft|ftp)
					    COMPREPLY=(ftp)
					    ;;
					s|sf|sft|sftp)
					    COMPREPLY=(sftp)
					    ;;
					t|tf|tft|tftp)
					    COMPREPLY=(tftp)
					    ;;
					'')
					    COMPREPLY=('' ftp sftp tftp)
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			denyurl)
			    case ${COMP_WORDS[3]} in
				set)
				    COMPREPLY=('' '<RET>' '<url>')
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	6)
	    case ${COMP_WORDS[1]} in
		rweb)
		    case ${COMP_WORDS[2]} in
			bypass)
			    case ${COMP_WORDS[3]} in
				application)
				    case ${COMP_WORDS[5]} in
					set)
					    case ${COMP_WORDS[6]} in
						c|cp|cpa|cpan|cpane|cpanel)
						    COMPREPLY=(cpanel)
						    ;;
						d)
						    COMPREPLY=('' dokuwiki drupal)
						    ;;
						'do'|dok|doku|dokuw|dokuwi|dokuwik|dokuwiki)
							COMPREPLY=('' dokuwiki drupal)
							;;
						dr|dru|drup|drupa|drupal)
						    COMPREPLY=(drupal)
						    ;;
						n|ne|nex|next|nextc|nextcl|nextclo|nextclou|nextcloud)
						    COMPREPLY=(nextcloud)
						    ;;
						w|wo|wor|word|wordp|wordpr|wordpre|wordpres|wordpress)
						    COMPREPLY=(wordpress)
						    ;;
						x|xe|xen|xenf|xenfo|xenfor|xenforo)
						    COMPREPLY=(xenforo)
						    ;;
						'')
						    COMPREPLY=('' '<RET>' cpanel dokuwiki drupal nextcloud wordpress xenforo)
						    ;;
						*)
						    COMPREPLY=()
						    ;;
					    esac
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				rule)
				    case ${COMP_WORDS[5]} in
					add|del)
					    COMPREPLY=('' '<rule-id>')
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			custom)
			    case ${COMP_WORDS[4]} in
				load|save)
				    case ${COMP_WORDS[5]} in
					ftp|sftp|tftp)
					    COMPREPLY=('' '<file-server>')
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	7)
	    case ${COMP_WORDS[1]} in
		rweb)
		    case ${COMP_WORDS[2]} in
			custom)
			    case ${COMP_WORDS[4]} in
				load|save)
				    case ${COMP_WORDS[5]} in
					ftp|sftp|tftp)
					    COMPREPLY=('' '<file-path>')
					    ;;
					*)
					    COMPREPLY=()
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	8)
	    case ${COMP_WORDS[1]} in
		rweb)
		    case ${COMP_WORDS[2]} in
			custom)
			    case ${COMP_WORDS[4]} in
				save)
				    case ${COMP_WORDS[5]} in
					ftp|sftp|tftp)
					    case ${COMP_WORDS[8]} in
						n|ne|new)
						    COMPREPLY=(new)
						    ;;
						'')
						    COMPREPLY=('' '<RET>' new)
						    ;;
						*)
						    COMPREPLY=()
						    ;;
					    esac
					    ;;
					*)
					    ;;
				    esac
				    ;;
				*)
				    COMPREPLY=()
				    ;;
			    esac
			    ;;
			*)
			    COMPREPLY=()
			    ;;
		    esac
		    ;;
		*)
		    COMPREPLY=()
		    ;;
	    esac
	    ;;
	*)
	    COMPREPLY=()
	    ;;
    esac

    test ${COMP_CWORD} -ge 4 || return 0

    if test ${COMP_WORDS[1]} == reputation -a ${COMP_WORDS[2]} == country ; then
	if test ${COMP_WORDS[3]} == add -o ${COMP_WORDS[3]} == del ; then
	    COMPREPLY=('' '<RET>' '<country-code>')
	fi
    fi
    
    test ${COMP_CWORD} -ge 6 || return 0

    if test ${COMP_WORDS[1]} == rweb -a ${COMP_WORDS[2]} == bypass -a ${COMP_WORDS[3]} == rule ; then
	if test ${COMP_WORDS[5]} == add -o ${COMP_WORDS[5]} == del ; then
	    COMPREPLY=('' '<RET>' '<rule-id>')
	fi
    fi
}
