#!/bin/bash

###########################################################################
#
# MODULE:       InitScript
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source /lib/lsb/init-functions

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role

PROG=clamd
FPROG=${LOCAL_DIR}/sbin/${PROG}

[ -x ${FPROG} ] || exit 0
[ -f ${LOCAL_DIR}/etc/${PROG}.conf ] || exit 0
[ -f /etc/sysconfig/${PROG} ] && source /etc/sysconfig/${PROG}

RETVAL=0
SERV="Antivirus"

AV_DEBUG=${AV_DEBUG-no}
AV_USER=${AV_USER-root}
AV_GROUP=${AV_GROUP-root}
AV_DB_DIR=${AV_DB_DIR-/var/clamav}
AV_TOTAL_TIMEOUT=${AV_TOTAL_TIMEOUT-180}
AV_TIMEOUT=${AV_TIMEOUT-500000}

wait4-bytecode()
{
    test -n "${1}" || return 1
    test -n "${2}" || return 2
    local retry=${1}
    local usleep=${2}

    local i=0

    while true
    do
	test ! -f ${AV_DB_DIR}/bytecode.cvd -a ! -f ${AV_DB_DIR}/bytecode.cld || break
	test ${i} -lt ${retry} || break
	usleep ${usleep}
	((i++))
    done

    test ${i} -lt ${retry}
}

# Main()

test ${AV_DEBUG} == no || DEBUG_OPTION=' --debug'

case "${1}" in
    start)
	log_info_msg "Starting ${SERV}..."
	wait4-bytecode $((AV_TOTAL_TIMEOUT * 1000000 / AV_TIMEOUT)) ${AV_TIMEOUT}
	start_daemon ${FPROG}${DEBUG_OPTION} --config-file=${LOCAL_DIR}/etc/clamd.conf 2> /dev/null
	RETVAL=${?}
	[ ${RETVAL} -eq 0 ] && touch /var/lock/${PROG}
	evaluate_retval
	exit ${RETVAL}
	;;

    stop)
	log_info_msg "Stopping ${SERV}..."
	killproc ${FPROG}
	RETVAL=${?}
	usleep 300000
	[ ${RETVAL} -eq 0 ] && rm -f /var/lock/${PROG} /var/run/clamav/${PROG}.pid
	evaluate_retval
	exit ${RETVAL}
	;;

    reload)
	[ -n "$(pidof ${PROG})" ] || exit 0
	log_info_msg "Reloading ${SERV} Signatures..."
	killproc ${FPROG} -USR2
	RETVAL=${?}
	[ ${RETVAL} -eq 0 ]
	evaluate_retval
	exit ${RETVAL}
	;;

    restart)
	${0} stop
	sleep 1
	${0} start
	;;
    
    status)
	statusproc ${PROG}
	;;

    *)
	echo "Usage: ${0} {start|stop|reload|restart|status}"
	exit 1
	;;
esac
