#!/bin/bash

###########################################################################
#
# MODULE:       InitScript
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source /lib/lsb/init-functions

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role

PROG="dhcpd"
FPROG="/sbin/${PROG}"

[ -f /etc/sysconfig/${PROG} ] && source /etc/sysconfig/${PROG}
[ -x ${FPROG} ] || exit 0
[ -f /etc/${PROG}.conf ] || exit 0
[ -f ${DB_DIR}/${PROG}.leases ] || touch ${DB_DIR}/${PROG}.leases

RETVAL=0
SERV="DHCP"

case "${1}" in
    start)
	[ -n "${DHCPD_IF}" ] || exit 11
	# Start daemons.
	log_info_msg "Starting ${SERV}..."
	start_daemon ${FPROG} -cf /etc/dhcpd.conf -lf ${DB_DIR}/${PROG}.leases ${DHCPD_IF} 2> /dev/null
	RETVAL=${?}
	[ ${RETVAL} -eq 0 ] && touch /var/lock/dhcpd
	evaluate_retval
	exit ${RETVAL}
	;;
    stop)
	# Stop daemons.
	log_info_msg "Stopping ${SERV}... "
	killproc ${FPROG}
	RETVAL=${?}
	usleep 500000
	[ ${RETVAL} -eq 0 ] && rm -f /var/lock/${PROG}
	evaluate_retval
	exit ${RETVAL}
	;;
    
    restart)
	${0} stop
	${0} start
	;;
    status)
	statusproc ${PROG}
	;;
    *)
	echo "Usage: ${0} {start|stop|restart|status}"
	exit 1
	;;
esac
