#!/bin/bash

###########################################################################
#
# MODULE:       InitScript
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source /lib/lsb/init-functions

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role

PROG="httpd"
RPROG="sbin/${PROG}"
FPROG="${WEB_SERVER_DIR}/${RPROG}"

CACHE_CLEAN_PROG="htcacheclean"

[ -x ${FPROG} ] || exit 0
[ -f ${WEB_SERVER_DIR}/etc/${PROG}.conf ] || exit 0

RETVAL=0
SERV="Web Server"

reset-waf-persistent-data()
{
    test -n "${WEB_SERVER_DIR}" || return 11
    test -d ${WEB_SERVER_DIR}/tmp || return 13
    rm -f ${WEB_SERVER_DIR}/tmp/*-{global,ip}.{pag,dir}
}

case "${1}" in
    start)
	# Start daemons.
	if [ -n "$(pidof ${PROG})" ]; then
	    echo $"${PROG}: already running"
	    exit 1
	fi
	
	log_info_msg "Starting ${SERV}..."
	rm -f ${WEB_RUN_DIR}/${PROG}.pid
	${FPROG} -f ${WEB_SERVER_DIR}/etc/${PROG}.conf 2> /dev/null
	RETVAL=${?}
	[ ${RETVAL} -eq 0 ] && touch /var/lock/${PROG}
	evaluate_retval
	exit ${RETVAL}
	;;

    stop)
	# Stop daemons.
	log_info_msg "Stopping ${SERV}..."
	killproc -p ${WEB_RUN_DIR}/${PROG}.pid ${FPROG}
	RETVAL=${?}
	usleep 500000
	[ ${RETVAL} -eq 0 ] && rm -f /var/lock/${PROG} ${WEB_RUN_DIR}/${PROG}.pid
	evaluate_retval
	reset-waf-persistent-data
	exit ${RETVAL}
	;;

    reload)
	log_info_msg "Reloading ${SERV}..."
	killproc -p ${WEB_RUN_DIR}/${PROG}.pid ${FPROG} -HUP
	RETVAL=${?}
	[ ${RETVAL} -eq 0 ]
	evaluate_retval
	exit ${RETVAL}
	;;

    clear)
	RETVAL1=$(pidof ${PROG})
	RETVAL2=$(pidof ${CACHE_CLEAN_PROG})

	test -z "${RETVAL1}" || ${0} stop
	/etc/rc.d/init.d/${CACHE_CLEAN_PROG} clear
	test -z "${RETVAL1}" || ${0} start
	test -z "${RETVAL2}" || /etc/rc.d/init.d/${CACHE_CLEAN_PROG} start
	;;

    restart)
	${0} stop
	${0} start
	;;
    
    status)
	statusproc ${PROG}
	;;

    *)
	echo "Usage: ${0} {start|stop|reload|clear|restart|status}"
	exit 1
	;;
esac
