#!/bin/bash

###########################################################################
#
# MODULE:       InitScript
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source /lib/lsb/init-functions

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source ${LOCAL_DIR}/lib/apl_common

PROG=ipsec
SUB_PROG=charon
FPROG=${LOCAL_DIR}/sbin/${PROG}

[ -f /etc/sysconfig/${PROG} ] && source /etc/sysconfig/${PROG}
[ -x ${FPROG} ] || exit 0
[ -f ${LOCAL_DIR}/etc/${PROG}.conf ] || exit 0

RETVAL=0
SERV="IPsec"

update-whitelist()
{
    test "${IPSEC_WHITELIST}" == yes || return 0

    wait4-file /var/run/${SUB_PROG}.wlst S 20 500000 || return 21
    if test -s ${VPN_IPSEC_DIR}/whitelist ; then
	usleep 500000
	${LOCAL_DIR}/libexec/ipsec/whitelist add-from ${VPN_IPSEC_DIR}/whitelist 2> /dev/null
    else
	${LOCAL_DIR}/libexec/ipsec/whitelist disable 2> /dev/null
    fi
}

case "${1}" in
    start)
	log_info_msg "Starting ${SERV}..."

	if [ -n "$(pidof ${SUB_PROG})" ]
	then
	    RETVAL=11
	    [ ${RETVAL} -eq 0 ]
	    evaluate_retval
	    exit ${RETVAL}
	fi

	${PROG} ${1} 2> /dev/null
	RETVAL=${?}

	if [ ${RETVAL} -ne 0 ]
	then
	    [ ${RETVAL} -eq 0 ]
	    evaluate_retval
	    exit ${RETVAL}
	fi

	update-whitelist

	RETVAL=${?}
	[ ${RETVAL} -eq 0 ] && touch /var/lock/${PROG}
	evaluate_retval
	exit ${RETVAL}
	;;

    stop)
	log_info_msg "Stopping ${SERV}..."

	if [ -z "$(pidof ${SUB_PROG})" ]
	then
	    RETVAL=1
	    [ ${RETVAL} -eq 0 ]
	    evaluate_retval
	    exit ${RETVAL}
	fi

	${PROG} ${1} 2> /dev/null
	usleep 300000

	if [ -z "$(pidof ${SUB_PROG})" ]
	then
	    RETVAL=0
	    rm -f /var/lock/${PROG}
	    rm -f /var/run/${SUB_PROG}.*
	else
	    RETVAL=3
	fi
	evaluate_retval
	exit ${RETVAL}
	;;

    reload)
	[ -n "$(pidof ${SUB_PROG})" ] || exit 0
	log_info_msg "Reloading ${SERV}..."

	${PROG} reload 2> /dev/null &&
	    ${PROG} secrets 2> /dev/null &&
	    update-whitelist
	RETVAL=${?}
	[ ${RETVAL} -eq 0 ]
	evaluate_retval
	exit ${RETVAL}
	;;

    restart)
	${0} stop
	sleep 1
	${0} start
	;;
    
    status)
	statusproc -p /var/run/${SUB_PROG}.pid ${SUB_PROG}
	;;

    *)
	echo "Usage: ${0} {start|stop|reload|restart|status}"
	exit 1
	;;
esac
