#!/bin/bash

###########################################################################
#
# MODULE:       InitScript
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

exit 0
source /lib/lsb/init-functions

PROG="lcd4linux"
FPROG=/bin/${PROG}

[ -f /etc/sysconfig/${PROG} ] && source /etc/sysconfig/${PROG}
[ -x ${FPROG} ] || exit 0
[ -f /etc/${PROG}.conf ] || exit 0

RETVAL=0
SERV="LCD Manager"

start()
{
    start_daemon ${FPROG} ${OPTIONS} -f /etc/${PROG}.conf
    RETVAL=${?}
    [ ${RETVAL} -eq 0 ] && touch /var/lock/${PROG}
    [ ${RETVAL} -eq 0 ]
    evaluate_retval
    return ${RETVAL}
}

stop()
{
    killproc ${PROG}
    RETVAL=${?}
    usleep 300000
    [ ${RETVAL} -eq 0 ] && rm -f /var/lock/${PROG}
    evaluate_retval
    return ${RETVAL}
}

case "${1}" in
    start)
	log_info_msg "Starting ${SERV}..."
	test -z "$(pidof ${PROG})" || stop
	start
	;;
    stop)
	log_info_msg "Stopping ${SERV}... "
	stop
	;;
    restart)
	${0} stop
	${0} start
	;;
    status)
	statusproc ${PROG}
	;;
    *)
	echo "Usage: ${0} {start|stop|restart|status}"
	exit 1
	;;
esac
