#!/bin/bash

###########################################################################
#
# MODULE:       InitScript
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source /lib/lsb/init-functions

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role

PROG="named"
FPROG=${LOCAL_DIR}/sbin/${PROG}
export KILL_CMD=/bin/kill

[ -f /etc/sysconfig/${PROG} ] && source /etc/sysconfig/${PROG}
[ -x ${FPROG} ] || exit 0
[ -f ${ROOT_DIR}/etc/${PROG}.conf ] || exit 0

RETVAL=0
SERV="DNS Service"

case "${1}" in
    start)
	# Start daemons.
	if [ -n "$(pidof ${PROG})" ]; then
	    echo $"${PROG}: already running"
	    exit 1
	fi
	log_info_msg "Starting ${SERV}..."
	start_daemon ${FPROG} ${OPTIONS}
	RETVAL=${?}
	if [ -z "$(pidof ${PROG})" ]; then
	    # The child processes have died after forking, e.g.
	    # because of a broken config file
	    RETVAL=1
	fi
	[ ${RETVAL} -eq 0 ] && touch /var/lock/${PROG}
	evaluate_retval
	exit ${RETVAL}
	;;
    stop)
	# Stop daemons.
	log_info_msg "Stopping ${SERV}... "
	killproc ${FPROG}
	RETVAL=${?}
	usleep 500000
	[ ${RETVAL} -eq 0 ] && rm -f /var/lock/${PROG}
	evaluate_retval
	exit ${RETVAL}
	;;
    reload)
	log_info_msg "Reloading ${SERV}..."
	killproc -p ${LOCAL_DIR}/var/${PROG}/var/${PROG}.pid ${FPROG} -HUP
	RETVAL=${?}
	[ ${RETVAL} -eq 0 ]
	evaluate_retval
	exit ${RETVAL}
	;;

    restart)
	${0} stop
	${0} start
	;;
    status)
	statusproc ${PROG}
	;;
    *)
	echo "Usage: ${0} {start|stop|reload|restart|status}"
	exit 1
	;;
esac
