#!/bin/bash

###########################################################################
#
# MODULE:       InitScript
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source /lib/lsb/init-functions

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role

PROG="ntpd"
FPROG=/usr/sbin/${PROG}
export KILL_CMD=/bin/kill

[ -f /etc/sysconfig/${PROG} ] && source /etc/sysconfig/${PROG}
[ -x ${FPROG} ] || exit 0
[ -x /usr/sbin/ntpdate ] || exit 0
[ -f /etc/ntp.conf ] || exit 0

[ -f ${HARD_DIR}/${INSTALL_DATE} ] || exit 0
[ -f ${HARD_DIR}/${VARIATION_DATE} ] || exit 0

RETVAL=0
SERV="NTP Service"

case "${1}" in
    start)
	[ -n "${NTP_SERVER_LIST}" ] || exit 0
	log_info_msg "Initialising ${SERV}..."
	for ntp_server in ${NTP_SERVER_LIST}
	do
	    date1=$(date +"%s" 2> /dev/null)
	    ntpdate -4 -t 5 ${ntp_server} > /dev/null 2> /dev/null
	    RETVAL=${?}

	    if test ${RETVAL} -eq 0 ; then
		date2=$(date +"%s" 2> /dev/null)
		vdate=$(cat ${HARD_DIR}/${VARIATION_DATE})
		echo -n $[${vdate} + ${date2} - ${date1}] > ${HARD_DIR}/${VARIATION_DATE}
	    fi

	    test ${RETVAL} -ne 0 || break
	done
	[ ${RETVAL} -eq 0 ]
	evaluate_retval
	test ${RETVAL} -eq 0 || exit ${RETVAL}
	
	# Start daemons.
	log_info_msg "Starting ${SERV}..."
	start_daemon ${FPROG} ${OPTIONS}
	RETVAL=$?
	[ ${RETVAL} -eq 0 ] && touch /var/lock/${PROG}
	evaluate_retval
	exit ${RETVAL}
	;;
    stop)
	# Stop daemons.
	log_info_msg "Stopping ${SERV}... "
	killproc ${FPROG}
	RETVAL=${?}
	usleep 300000
	[ ${RETVAL} -eq 0 ] && rm -f /var/lock/${PROG}
	evaluate_retval
	exit ${RETVAL}
	;;
    
    restart)
	${0} stop
	${0} start
	;;
    status)
	statusproc ${PROG}
	;;
    *)
	echo "Usage: ${0} {start|stop|restart|status}"
	exit 1
	;;
esac
