#!/bin/bash

###########################################################################
#
# MODULE:       InitScript
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source /lib/lsb/init-functions

CACHEGUARD_DIR=/etc/sysconfig/cacheguard
source ${CACHEGUARD_DIR}/constant
source ${APPLIANCE_DIR}/etc/role
source ${LOCAL_DIR}/lib/apl_common
source ${LOCAL_DIR}/lib/apl_net

PROG="supervisor"
SERV="Supervisor"
RETVAL=0

init-supervisor()
{
    rm -f ${RUN_DIR}/${SUPERVISOR_FIFO} &&
	mkfifo -m 664 ${RUN_DIR}/${SUPERVISOR_FIFO} &&
	chown ${ADMIN_NAME}:${GROUP_NAME} ${RUN_DIR}/${SUPERVISOR_FIFO}
}

case "${1}" in
    start)
	init-supervisor
	log_info_msg "Starting ${SERV}..."

	if test -s /var/run/${PROG}.pid ; then
	     RETVAL=21
	     [ ${RETVAL} -eq 0 ]
	     evaluate_retval
	     exit ${RETVAL}
	fi

	# Start daemons.
	nice --adjustment=-18 /usr/local/bin/apl_supervisord < /dev/console > /dev/null 2>&1 &
	RETVAL=${?}
	echo ${!} > /var/run/${PROG}.pid
	[ ${RETVAL} -eq 0 ] && touch /var/lock/${PROG}
	evaluate_retval
	exit ${RETVAL}
	;;
    stop)
	# Stop daemons.
	log_info_msg "Stopping ${SERV}... "

	if test ! -s /var/run/${PROG}.pid ; then
	     RETVAL=21
	     [ ${RETVAL} -eq 0 ]
	     evaluate_retval
	     exit ${RETVAL}
	fi

	SUPERVISOR_PID=$(cat /var/run/${PROG}.pid 2> /dev/null)
	ps -p ${SUPERVISOR_PID} > /dev/null 2>&1
	RETVAL=${?}
	if [ ${RETVAL} -eq 1 ] ; then
	    rm -f /var/lock/${PROG}
	    rm -f /var/run/${PROG}.pid
	else
	    kill -SIGKILL ${SUPERVISOR_PID} 2> /dev/null
	    RETVAL=${?}
	    usleep 300000
	    [ ${RETVAL} -eq 0 ] && rm -f /var/lock/${PROG} &&
		rm -f /var/run/${PROG}.pid &&
		rm -f ${RUN_DIR}/${SUPERVISOR_FIFO}
	fi
	[ ${RETVAL} -eq 0 ]
	evaluate_retval
	exit ${RETVAL}
	;;
    restart)
	${0} stop
	${0} start
	;;
    status)
	statusproc ${PROG}
	;;
    *)
	echo "Usage: ${0} {start|stop|restart|status}"
	exit 11
	;;
esac
