#!/bin/bash

###########################################################################
#
# MODULE:       Commands
# AUTHOR(S):    CacheGuard Development Team
#
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

source #APPLIANCE_DIR#/etc/constant

show-prompt()
{
    local base=$(cat ${ADMIN_DIR}/.prompt 2> /dev/null) in_context

    if test -s ${HOME}/${MANAGER_CONF_CONTEXT_FILE} ; then
	in_context=/$(cat ${HOME}/${MANAGER_CONF_CONTEXT_FILE} 2> /dev/null)
	in_context=${in_context/ /:}
    elif test -f ${HOME}/${MANAGER_EXEC_CONTEXT_FILE} ; then

	local context place domain id ip
	read context place domain id ip < ${HOME}/${MANAGER_EXEC_CONTEXT_FILE}

	case ${context} in
	    template)
		in_context=${context}
		;;
	    gateway)
		in_context="${context} ${place}"
		;;
	    *)
		;;
	esac
	in_context="[${in_context} exec]"
    fi

    local prompt=${base}${in_context}

    echo ${prompt}
}

# Main()

show-prompt
