#!/bin/bash

###########################################################################
#
# MODULE:       Build
# AUTHOR(S):    CacheGuard Development Team
# COPYRIGHT:    (C) 2009-2025 by CacheGuard Technologies Ltd (UK)
# COPYRIGHT:    (C) 2026-2026 by CacheGuard Technologies SAS (FR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

test -n "${APL}" || exit 1
test -d "${APL}" || exit 2

source CacheGuard.env
source Tuner/TUNER.env

get-admin-relative-dir()
{
    local dir=${1}
    
    local len=${#ADMIN_DIR}
    echo ${dir:${len}}
}

gen-tmp-conf-files()
{
    echo -n 'export TMP_CONF_FILES="'
    echo -n '${TLS_SERVER}.*.conf'
    echo -n ' ${TLS_SERVER}.*.2sign'
    echo -n ' ${TLS_SERVER}.*.2rev'
    echo -n ' ${TLS_CLIENT}.*.2rev'
    echo -n ' ${SYSTEM_CA}.conf'
    echo -n ' ${LOADED}.${SNMP_SSL}.certificate'
    echo -n ' ${LOADED}.${AV_WHITELIST_SIG}'
    echo -n ' ${LOADED}.${TLS_SERVER}.key.*'
    echo -n ' ${LOADED}.${TLS_SERVER}.certificate.*'
    echo -n ' ${LOADED}.${TLS_SERVER}.csr.*'
    echo -n ' ${LOADED}.${TLS_SERVER}.days.*'
    echo -n ' ${LOADED}.${TLS_CLIENT}.certificate.*'
    echo -n ' ${LOADED}.${SYSTEM_CA}.key'
    echo -n ' ${LOADED}.${SYSTEM_CA}.certificate'
    echo -n ' ${LOADED}.${THIRD_CA}.*'
    echo -n ' ${LOADED}.${SSH_KEY}.*'
    echo -n ' ${LOADED}.manager.${SSH_KEY}.*'
    echo -n ' ${LOADED}.os.tar.compressed'
    echo -n ' ${LOADED}.backup'
    echo -n ' ${ADMIN_USER_PASSWD}.*'
    echo -n ' ${URLLIST_CLEAR}.*.*'
    echo -n ' ${REGISTER_EMAIL}'
    echo -n ' ${REGISTER_OTP}'
    echo -n ' ${REGISTER_KEY}'
    echo -n ' ${EMBEDDED_VPNSUBSCR_REGISTER_KEY}'    
    echo -n ' ${UNREGISTER_SN}'
    echo -n ' ${AV_WHITELIST_SIG}.2del'
    echo -n ' ${SSH_HOST_ARM_NEW}'
    echo -n ' ${SSH_MANAGER_ARM_NEW}'
    echo '"'
}

gen-common-constant()
{
    cat <<EOF
#############################
# NEVER EVER EDIT THIS FILE #
#############################

EOF
    echo "TECHNICAL_NAME=${TECHNICAL_NAME}"
    echo "DEFAULT_CA_CN='${DEFAULT_CA_CN}'"

    echo "WEBSITE=${WEBSITE}"
    echo "YEARS=${YEARS}"
    echo "PATCH_SERVER=${PATCH_SERVER}"
    echo "FINGERPRINT_URL=${FINGERPRINT_URL}"
    echo "PATCH_URL=${PATCH_URL}"
    echo "MY_PUBLIC_IP_URL=${MY_PUBLIC_IP_URL}"
    echo "LATEST_VERSION_URL=${LATEST_VERSION_URL}"

    echo "COMMERCIAL_NAME=${COMMERCIAL_NAME}"
    echo "COMPANY_NAME='${COMPANY_NAME}'"
    echo "COMMERCIAL_MODEL=${COMMERCIAL_MODEL}"
    echo "OS_GENERATION=${OS_GENERATION}"
    echo "OS_FREE_USAGE=${OS_FREE_USAGE}"
    echo "SUPERADMIN_NAME=${SUPERADMIN_NAME}"
    echo "WADMIND_NAME=${WADMIND_NAME}"
    echo "ADMIN_NAME=${ADMIN_NAME}"
    echo "MANAGER_NAME=${MANAGER_NAME}"
    echo "WADMIN_NAME=${WADMIN_NAME}"
    echo "WAUDIT_NAME=${WAUDIT_NAME}"
    echo "GROUP_NAME=${GROUP_NAME}"
    echo "MASTER_MANAGER_NAME=${MASTER_MANAGER_NAME}"
    echo "BACKUP_MANAGER_NAME=${BACKUP_MANAGER_NAME}"
    echo "PEER_MANAGER_NAME=${PEER_MANAGER_NAME}"
    echo "WAUDIT_BINARY_FILES='${WAUDIT_BINARY_FILES}'"

    echo "SUPERVISOR_FIFO=${SUPERVISOR_FIFO}"
    echo "SUPERVISOR_ARGS=${SUPERVISOR_ARGS}"
    echo "WAITING_PROCESS=${WAITING_PROCESS}"

    echo "GUI_MODULE_NAME=Administration"
    echo "GUI_HOME_PAGE=${GUI_HOME_PAGE}"
    echo "GUI_COOKIE_AUTH_NAME=${GUI_COOKIE_AUTH_NAME}"
    echo "GUI_COOKIE_CONTEXT_NAME=${GUI_COOKIE_CONTEXT_NAME}"
    echo "GUI_COOKIE_LEFT_MENU_NAME=${GUI_COOKIE_LEFT_MENU_NAME}"
    echo "GUI_COOKIE_TOP_MENU_NAME=${GUI_COOKIE_TOP_MENU_NAME}"
    echo "GUI_COOKIE_DASHBOARD_MENU_NAME=${GUI_COOKIE_DASHBOARD_MENU_NAME}"
    echo "GUI_CSRF_ATTRIBUTE=${GUI_CSRF_ATTRIBUTE}"
    echo "GUI_AUTHENTICATION_KEY_FILE=${GUI_AUTHENTICATION_KEY_FILE}"

    echo "WAF_RDIR=${WAF_RDIR}"
    echo "VPN_IPSEC_RDIR=${VPN_IPSEC_RDIR}"
    echo "URLLIST_RDIR=${URLLIST_RDIR}"
    echo "SSH_PUBLIC_KEY_RDIR=${SSH_PUBLIC_KEY_RDIR}"

    echo "MANAGER_REPOSITORY_RDIR=${MANAGER_REPOSITORY_RDIR}"
    echo "MANAGER_TEMPLATE_RDIR=${MANAGER_TEMPLATE_RDIR}"
    echo "MANAGER_GATEWAY_RDIR=${MANAGER_GATEWAY_RDIR}"
    echo "MANAGER_GATEWAY_INDEX=${MANAGER_GATEWAY_INDEX}"
    echo "AUDIT_RDIR=${AUDIT_RDIR}"

    echo "SSL_RDIR=${SSL_RDIR}"
    echo "SSL_SERVER_RDIR=${SSL_SERVER_RDIR}"
    echo "SSL_CA_RDIR=${SSL_CA_RDIR}"
    echo "SSL_LOCAL_CA_RDIR=${SSL_LOCAL_CA_RDIR}"
    echo "SSL_CLIENT_RDIR=${SSL_CLIENT_RDIR}"
    echo "SSL_CTL_RDIR=${SSL_CTL_RDIR}"
    echo "SSL_SNMP_RDIR=${SSL_SNMP_RDIR}"

    echo "ENV_RDIR=${ENV_RDIR}"
    echo "ENV_NAME=${ENV_NAME}"
    echo "ENV_CURRENT_NAME=${ENV_CURRENT_NAME}"
    echo "ENV_CANCEL_NAME=${ENV_CANCEL_NAME}"
    echo "ENV_FACTORY_NAME=${ENV_FACTORY_NAME}"
    echo "ENV_CURRENT_FACTORY_NAME=${ENV_CURRENT_FACTORY_NAME}"
    echo "ENV_NOT_RESOLVED_NAME=${ENV_NOT_RESOLVED_NAME}"

    echo "CONFIGURATION_DB_NAME=${CONFIGURATION_DB_NAME}"
    echo "CONFIGURATION_CURRENT_DB_NAME=${CONFIGURATION_CURRENT_DB_NAME}"
    echo "CONFIGURATION_FACTORY_DB_NAME=${CONFIGURATION_FACTORY_DB_NAME}"
    echo "CONFIGURATION_CURRENT_FACTORY_DB_NAME=${CONFIGURATION_CURRENT_FACTORY_DB_NAME}"

    echo "SN_PREFIX=${SN_PREFIX}"
    echo "SN_ID=${SN_ID}"
    echo "SN_IP=${SN_IP}"
    echo "SN_PASSWD=${SN_PASSWD}"
    echo "SN_ALIVE=${SN_ALIVE}"

    echo "ADMIN_USER_PASSWD=${ADMIN_USER_PASSWD}"

    echo "REGISTER_EMAIL=${REGISTER_EMAIL}"
    echo "REGISTER_OTP=${REGISTER_OTP}"
    echo "REGISTER_KEY=${REGISTER_KEY}"
    echo "UNREGISTER_SN=${UNREGISTER_SN}"
    echo "REGISTER_STATE=${REGISTER_STATE}"

    echo "LIC_KEY=${LIC_KEY}"
    echo "LIC_USERS_NB_0=${LIC_USERS_NB_0}"
    echo "LIC_USERS_NB_1=${LIC_USERS_NB_1}"
    echo "LIC_USERS_NB_2=${LIC_USERS_NB_2}"

    echo "LIC_RUSERS_NB_0=${LIC_RUSERS_NB_0}"
    echo "LIC_RUSERS_NB_1=${LIC_RUSERS_NB_1}"
    echo "LIC_RUSERS_NB_2=${LIC_RUSERS_NB_2}"

    echo "LIC_GATEWAYS_NB_0=${LIC_GATEWAYS_NB_0}"
    echo "LIC_GATEWAYS_NB_1=${LIC_GATEWAYS_NB_1}"
    echo "LIC_GATEWAYS_NB_2=${LIC_GATEWAYS_NB_2}"

    echo "NOPROGRESS_TERM=${NOPROGRESS_TERM}"
    echo "PROGRESS=${PROGRESS}"
    echo "SIGNATURE=${SIGNATURE}"
    echo "CLOCK_2SAVE=${CLOCK_2SAVE}"
    echo "NAME_2RESOLVE=${NAME_2RESOLVE}"
    echo "TLS_SERVER=${TLS_SERVER}"
    echo "TLS_CLIENT=${TLS_CLIENT}"
    echo "THIRD_CA=${THIRD_CA}"
    echo "WAF_RWEB_CUSTOM=${WAF_RWEB_CUSTOM}"
    echo "SSH_KEY=${SSH_KEY}"
    echo "ICA=${ICA}"
    echo "LOADED=${LOADED}"
    echo "ILOADED=${ILOADED}"
    echo "MPUSHED=${MPUSHED}"
    echo "MPUSHED_STATUS=${MPUSHED_STATUS}"
    echo "SAVED=${SAVED}"
    echo "AV_WHITELIST_SIG=${AV_WHITELIST_SIG}"
    echo "AV_WHITELIST_DOMAIN_FILENAME=${AV_WHITELIST_DOMAIN_FILENAME}"
    echo "AV_REGULAR_DB_SZ_FILENAME=${AV_REGULAR_DB_SZ_FILENAME}"
    echo "AV_REGULAR_DB_DOWNLOADED_SZ_FILENAME=${AV_REGULAR_DB_DOWNLOADED_SZ_FILENAME}"

    echo "SNMP_SSL=${SNMP_SSL}"
    echo "SYSTEM_CA=${SYSTEM_CA}"
    echo "SYSTEM_CA_ID=${SYSTEM_CA_ID}"
    echo "URLLIST_AUTO=${URLLIST_AUTO}"

    echo "QOS_INDEX_FILENAME=${QOS_INDEX_FILENAME}"
    echo "QOS_TRAFFIC_FILENAME=${QOS_TRAFFIC_FILENAME}"
    echo "QOS_DIFF_TRAFFIC_FILENAME=${QOS_DIFF_TRAFFIC_FILENAME}"
    echo "VPN_IPSEC_STATUS_FILENAME=${VPN_IPSEC_STATUS_FILENAME}"
    echo "SUSPENSION_STATE_FILENAME=${SUSPENSION_STATE_FILENAME}"
    echo "SERVICES_STATE_FILENAME=${SERVICES_STATE_FILENAME}"
    echo "HEALTH_STATE_FILENAME=${HEALTH_STATE_FILENAME}"
    echo "LINKS_STATE_FILENAME=${LINKS_STATE_FILENAME}"
    echo "GATEWAYS_STATE_FILENAME=${GATEWAYS_STATE_FILENAME}"
    echo "VPN_IPSEC_SITE_STATE_FILENAME=${VPN_IPSEC_SITE_STATE_FILENAME}"
    echo "CONNECTION_FILENAME=${CONNECTION_FILENAME}"
    echo "CONNECTION_SUMMARY_FILENAME=${CONNECTION_SUMMARY_FILENAME}"
    echo "TLS_SYSTEM_CA_STATE_FILENAME=${TLS_SYSTEM_CA_STATE_FILENAME}"
    echo "TLS_THIRD_CA_STATE_FILENAME=${TLS_THIRD_CA_STATE_FILENAME}"
    echo "TLS_SERVER_STATE_FILENAME=${TLS_SERVER_STATE_FILENAME}"
    echo "TLS_CLIENT_STATE_FILENAME=${TLS_CLIENT_STATE_FILENAME}"
    echo "DYNAMIC_DNS_STATE_FILENAME=${DYNAMIC_DNS_STATE_FILENAME}"
    echo "DISKS_STATS_IO_FILENAME=${DISKS_STATS_IO_FILENAME}"
    echo "DISKS_STATS_TIME_IO_FILENAME=${DISKS_STATS_TIME_IO_FILENAME}"
    echo "DISKS_STATS_AVG_FILENAME=${DISKS_STATS_AVG_FILENAME}"
    echo "DISKS_HEALTH_FILENAME=${DISKS_HEALTH_FILENAME}"
    echo "RAID_HEALTH_FILENAME=${RAID_HEALTH_FILENAME}"
    echo "USED_RCACHE_FILENAME=${USED_RCACHE_FILENAME}"
    echo "MEAN_OBJECT_SZ_FILENAME=${MEAN_OBJECT_SZ_FILENAME}"
    echo "TOTAL_IN_MEMORY_CACHED_OBJECT_SZ_FILENAME=${TOTAL_IN_MEMORY_CACHED_OBJECT_SZ_FILENAME}"
    echo "KERBEROS_CREATE_FILENAME=${KERBEROS_CREATE_FILENAME}"
    echo "IP_NEIGHBOUR_FILENAME=${IP_NEIGHBOUR_FILENAME}"
    
    echo "AV_EXTENDED_DB_SZ_FILENAME=${AV_EXTENDED_DB_SZ_FILENAME}"
    echo "AV_EXTENDED_DB_DOWNLOADED_SZ_FILENAME=${AV_EXTENDED_DB_DOWNLOADED_SZ_FILENAME}"
    echo "AV_EXTENDED_PACK_SZ_FILENAME=${AV_EXTENDED_PACK_SZ_FILENAME}"
    echo "AV_EXTENDED_PACK_DOWNLOADED_SZ_FILENAME=${AV_EXTENDED_PACK_DOWNLOADED_SZ_FILENAME}"
    
    echo "AV_EXTENDED_INDEX_FILENAME=${AV_EXTENDED_INDEX_FILENAME}"
    echo "AV_EXTENDED_LAST_UPDATE_FILENAME=${AV_EXTENDED_LAST_UPDATE_FILENAME}"
    echo "AV_EXTENDED_PUSHED_NAME=${AV_EXTENDED_PUSHED_NAME}"

    echo "CPU_STATISTICS_FILENAME=${CPU_STATISTICS_FILENAME}"
    echo "CPU_USAGE_FILENAME=${CPU_USAGE_FILENAME}"

    echo "NETWORK_STATISTICS_FILENAME=${NETWORK_STATISTICS_FILENAME}"
    echo "NETWORK_INTERFACES_FILENAME=${NETWORK_INTERFACES_FILENAME}"
    echo "SSLMEDIATE_EXCEPTIONS_FILENAME=${SSLMEDIATE_EXCEPTIONS_FILENAME}"

    echo "SNMP_ENGINE_ID=${SNMP_ENGINE_ID}"
    echo "STATISTICS_INTERVAL=10"
    echo "STATISTICS_HISTORY=900"

    echo "URLLIST=${URLLIST}"
    echo "URLLIST_CREATE=${URLLIST_CREATE}"
    echo "URLLIST_UPDATE=${URLLIST_UPDATE}"
    echo "URLLIST_CLEAR=${URLLIST_CLEAR}"

    echo "FIRST_STARTUP=${FIRST_STARTUP}"
    echo "FIRST_LOGIN=${FIRST_LOGIN}"
    echo "INSTALL_DATE=${INSTALL_DATE}"
    echo "ALIVE_DATE=${ALIVE_DATE}"
    echo "VARIATION_DATE=${VARIATION_DATE}"

    echo "SERIAL_DATE=${SERIAL_DATE}"
    echo "RENEW_DAYS=${RENEW_DAYS}"
    echo "TRIAL_PERIOD=${TRIAL_PERIOD}"
    echo "TRIAL_PERIOD_MARGIN=${TRIAL_PERIOD_MARGIN}"
    echo "LICENSE_PERIOD=${LICENSE_PERIOD}"

    echo "LOCAL_DIR=${LOCAL_DIR}"
    echo "PRIVATE_DIR=${PRIVATE_DIR}"
    echo "PROXY_DIR=${PROXY_DIR}"
    echo "WEB_SERVER_DIR=${WEB_SERVER_DIR}"
    echo "IMAGE_DIR=/${IMAGE_DIR_NAME}"
    echo "JS_DIR=/${JS_DIR_NAME}"
    echo "HARD_DIR_NAME=${HARD_DIR_NAME}"
    echo "PATCH_DIR_NAME=${PATCH_DIR_NAME}"
    echo "ADMIN_LOCK_DIR=$(get-admin-relative-dir ${LOCK_DIR})"

    echo "CGI_DIR_NAME=${CGI_DIR_NAME}"
    echo "GUI_DIR_NAME=${GUI_DIR_NAME}"
    echo "GUI_EXT_NAME=${GUI_EXT_NAME}"
    echo "GUI_PAGES_HIERARCHY_FILENAME=${GUI_PAGES_HIERARCHY_FILENAME}"
    echo "GUI_DASHBOARD_LAYOUT_FILENAME=${GUI_DASHBOARD_LAYOUT_FILENAME}"
    echo "GUI_CORE_EXT=${GUI_CORE_EXT}"

    echo "COMMANDS=\"${COMMANDS}\""

    echo "BACKUP_PASSWD=${BACKUP_PASSWD}"
    echo "FILE_PASSWD=${FILE_PASSWD}"
    echo "LDAP_PASSWD=${LDAP_PASSWD}"
    echo "KERBEROS_SHARED_PASSWD=${KERBEROS_SHARED_PASSWD}"
    echo "EMAIL_PASSWD=${EMAIL_PASSWD}"
    echo "SNMP_PASSWD=${SNMP_PASSWD}"
    echo "WAF_REPUTATION_RBL_PASSWD=${WAF_REPUTATION_RBL_PASSWD}"
    echo "DYNDNS_PASSWD=${DYNDNS_PASSWD}"
    echo "IPSEC_PASSWD=${IPSEC_PASSWD}"
    echo "IPSEC_AUTHENTICATE_PSK_FILENAME=${IPSEC_AUTHENTICATE_PSK_FILENAME}"

    echo "VPN_IPSEC_REMOTE_ACCESS_DEFAULT_NETWORK=172.17.0.0"
    echo "VPN_IPSEC_REMOTE_ACCESS_DEFAULT_NETMASK=255.255.0.0"
    echo "VPN_IPSEC_REMOTE_ACCESS_DEFAULT_PREFIX=16"

    echo "LOG_TAG_NIL=${LOG_TAG_NIL}"
    echo "LOG_TAG_AV_REGULAR=${LOG_TAG_AV_REGULAR}"
    echo "LOG_TAG_SSLMEDIATE=${LOG_TAG_SSLMEDIATE}"
    echo "LOG_TAG_AV_EXTENDED_UPDATE=${LOG_TAG_AV_EXTENDED_UPDATE}"
    echo "LOG_TAG_AV_EXTENDED_CREATE=${LOG_TAG_AV_EXTENDED_CREATE}"

    echo "FIREWALL_LOG=${FIREWALL_LOG}"
    echo "ANTI_VIRUS_LOG=${ANTI_VIRUS_LOG}"
    echo "ANTI_VIRUS_SERVER_LOG=${ANTI_VIRUS_SERVER_LOG}"
    echo "ACCESS_GUARD_LOG=${ACCESS_GUARD_LOG}"
    echo "WAF_LOG=${WAF_LOG}"
    echo "WEB_LOG=${WEB_LOG}"
    echo "RWEB_LOG=${RWEB_LOG}"
    echo "VPN_IPSEC_LOG=${VPN_IPSEC_LOG}"

    echo "COUNTER_POSTFIX=${COUNTER_POSTFIX}"
    echo "COUNTER_DATE_POSTFIX=${COUNTER_DATE_POSTFIX}"
    
    echo "AUTH_LDAP_TEST=${AUTH_LDAP_TEST}"

    echo "MAX_REGEXP_LEN=${MAX_REGEXP_LEN}"
    echo "MAX_URLLIST_NB=${MAX_URLLIST_NB}"
    echo "MAX_WAF_RULES_NB=${MAX_WAF_RULES_NB}"
    echo "MAX_ADMINISTRATORS_NB=${MAX_ADMINISTRATORS_NB}"
    echo "MAX_SSH_KEY_NB=${MAX_SSH_KEY_NB}"
    echo "MAX_CA_NB=64"
    echo "MAX_VPN_NB=128"
    echo "MAX_NAME_LEN=22"
    echo "MAX_URLLIST_GZ_SZ=$[128 * 1024]"

    echo "LDAP_CONNECTION_TIMEOUT=5"
    echo "TLS_NB_FACTOR=3"

    echo "COMMAND_TAG=XYZ-COMMAND-20221230-09:29"
    echo "ERROR_TAG=XYZ-ERROR-20221230-09:29"
    echo "WARNING_TAG=XYZ-WARNING-20221230-09:29"
    echo "INFO_TAG=XYZ-INFO-20221230-09:29"

    echo "DEFAULT_TIMEZONE='${TEST_TIMEZONE}'"
    echo "DEFAULT_IP_EXTERNAL_IP='${TEST_IP_EXTERNAL_IP}'"
    echo "DEFAULT_IP_EXTERNAL_MASK='${TEST_IP_EXTERNAL_MASK}'"
    echo "DEFAULT_DNS_MODE='${TEST_DNS_MODE}'"
    echo "DEFAULT_NAME_SERVER_LIST='${TEST_NAME_SERVER_LIST}'"
    echo "DEFAULT_ACCESS_FILE_LIST='${TEST_ACCESS_FILE_LIST}'"
    echo "DEFAULT_ACCESS_MON_LIST='${TEST_ACCESS_MON_LIST}'"

    echo "DEFAULT_GATEWAY_IP_INTERNAL_IP='${TEST_GATEWAY_IP_INTERNAL_IP}'"
    echo "DEFAULT_GATEWAY_IP_INTERNAL_MASK='${TEST_GATEWAY_IP_INTERNAL_MASK}'"
    echo "DEFAULT_GATEWAY_IP_ROUTE_LIST='${TEST_GATEWAY_IP_ROUTE_LIST}'"

    echo "DEFAULT_MANAGER_BOND_INTERNALS='${TEST_MANAGER_BOND_INTERNALS}'"
    echo "DEFAULT_MANAGER_BOND_EXTERNALS='${TEST_MANAGER_BOND_EXTERNALS}'"
    echo "DEFAULT_MANAGER_IP_INTERNAL_IP='${TEST_MANAGER_IP_INTERNAL_IP}'"
    echo "DEFAULT_MANAGER_IP_INTERNAL_MASK='${TEST_MANAGER_IP_INTERNAL_MASK}'"
    echo "DEFAULT_MANAGER_IP_ROUTE_LIST='${TEST_MANAGER_IP_ROUTE_LIST}'"
    echo "DEFAULT_MANAGER_DNS_IP='${TEST_MANAGER_DNS_IP}'"

    echo "SSH_HOST_RSA_FP=${SSH_HOST_RSA_FP}"
    echo "SSH_HOST_ARM_NEW=${SSH_HOST_ARM_NEW}"
    echo "SSH_MANAGER_ARM_NEW=${SSH_MANAGER_ARM_NEW}"

    echo "MODIFICATION_STATE_FILENAME=${MODIFICATION_STATE_FILENAME}"

    echo "TWO_FACTOR_AUTHENTICATION=${TWO_FACTOR_AUTHENTICATION}"
    echo "TWO_FACTOR_GOOGLE_AUTHENTICATOR=${TWO_FACTOR_GOOGLE_AUTHENTICATOR}"
    echo "TWO_FACTOR_AUTHENTICATION_STEP_SIZE=${TWO_FACTOR_AUTHENTICATION_STEP_SIZE}"
    echo "TWO_FACTOR_AUTHENTICATION_WINDOW_SIZE=${TWO_FACTOR_AUTHENTICATION_WINDOW_SIZE}"

    echo "EMBEDDED_VPNSUBSCR_APP_CODE=${EMBEDDED_VPNSUBSCR_APP_CODE}"
    echo "EMBEDDED_UNKNOWN_APP_CODE=${EMBEDDED_UNKNOWN_APP_CODE}"

    echo "EMBEDDED_VPNSUBSCR_REGISTER_KEY=${EMBEDDED_VPNSUBSCR_REGISTER_KEY}"
    echo "EMBEDDED_APPLICATIONS_NAME=${EMBEDDED_APPLICATIONS_NAME}"
    echo "EMBEDDED_VPNSUBSCR_NAME=${EMBEDDED_VPNSUBSCR_NAME}"
    echo "EMBEDDED_VPNSUBSCR_COMMERCIAL_NAME='${EMBEDDED_VPNSUBSCR_COMMERCIAL_NAME}'"
    echo "EMBEDDED_VPNSUBSCR_CLI_NAME='${EMBEDDED_VPNSUBSCR_CLI_NAME}'"

    gen-tmp-conf-files
}

gen-admin-constant()
{
    gen-common-constant

    echo "LICENSE_PERIOD_MARGIN_1=${LICENSE_PERIOD_MARGIN_1}"

    echo "APPLIANCE_WEBSITE=${APPLIANCE_WEBSITE}"
    echo "DONATE_URL=${DONATE_URL}"
    echo "REGISTER_URL=${REGISTER_URL}"
    echo "SUBSCRIBE_URL=${SUBSCRIBE_URL}"
    echo "PATCH_VERSION_URL=${PATCH_VERSION_URL}"
    echo "LICENSE_URL=${LICENSE_URL}"

    echo "DEFAULT_COUNTRY_CODE=${DEFAULT_COUNTRY_CODE}"
    echo "DEFAULT_COUNTRY_NAME='${DEFAULT_COUNTRY_NAME}'"

    echo "RUNTIME_ENV_DIR=$(get-admin-relative-dir ${RUNTIME_ENV_DIR})"

    echo "WAUTH_LOG=$(get-admin-relative-dir ${WAUTH_LOG})"
    echo "APPLY_LOG=$(get-admin-relative-dir ${APPLY_LOG})"
    echo "CACHE_CLEAR_LOG=$(get-admin-relative-dir ${CACHE_CLEAR_LOG})"
    echo "AV_CREATE_LOG=$(get-admin-relative-dir ${AV_CREATE_LOG})"
    echo "AV_UPDATE_LOG=$(get-admin-relative-dir ${AV_UPDATE_LOG})"
    echo "LOG_ROTATE_LOG=$(get-admin-relative-dir ${LOG_ROTATE_LOG})"
    echo "URLLIST_AUTO_LOG=$(get-admin-relative-dir ${URLLIST_AUTO_LOG})"
    echo "BACKUP_LOG=$(get-admin-relative-dir ${BACKUP_LOG})"
    echo "FILE_OPERATION_LOG=$(get-admin-relative-dir ${FILE_OPERATION_LOG})"
    echo "KERBEROS_CREATE_LOG=$(get-admin-relative-dir ${KERBEROS_CREATE_LOG})"
    echo "AV_AUTO_UPDATE_FILE=$(get-admin-relative-dir ${AV_AUTO_UPDATE_FILE})"
    echo "MANAGER_PULL_OPERATION_LOG=$(get-admin-relative-dir ${MANAGER_PULL_OPERATION_LOG})"
    echo "MANAGER_PUSH_OPERATION_LOG=$(get-admin-relative-dir ${MANAGER_PUSH_OPERATION_LOG})"
    echo "MANAGER_TEMPLATE_EXEC_OPERATION_LOG=$(get-admin-relative-dir ${MANAGER_TEMPLATE_EXEC_OPERATION_LOG})"
    echo "MANAGER_LOCAL_EXEC_OPERATION_LOG=$(get-admin-relative-dir ${MANAGER_LOCAL_EXEC_OPERATION_LOG})"
    echo "MANAGER_REMOTE_EXEC_OPERATION_LOG=$(get-admin-relative-dir ${MANAGER_REMOTE_EXEC_OPERATION_LOG})"
    echo "MANAGER_SYNC_FILE=$(get-admin-relative-dir ${MANAGER_SYNC_FILE})"
    
    echo "ETC_DIR=$(get-admin-relative-dir ${ETC_DIR})"
    echo "HARD_DIR=$(get-admin-relative-dir ${HARD_DIR})"
    echo "TMP_DIR=$(get-admin-relative-dir ${TMP_DIR})"
    echo "ADMIN_TMP_DIR=$(get-admin-relative-dir ${TMP_DIR})"
    echo "TMP_TEMPLATE_DIR=$(get-admin-relative-dir ${TMP_TEMPLATE_DIR})"
    echo "TMP_GATEWAY_DIR=$(get-admin-relative-dir ${TMP_GATEWAY_DIR})"
    echo "SSL_DIR=$(get-admin-relative-dir ${SSL_DIR})"
    echo "SSL_CA_DIR=$(get-admin-relative-dir ${SSL_CA_DIR})"
    echo "SSL_LOCAL_CA_DIR=$(get-admin-relative-dir ${SSL_LOCAL_CA_DIR})"
    echo "SSL_SERVER_DIR=$(get-admin-relative-dir ${SSL_SERVER_DIR})"
    echo "SSL_CLIENT_DIR=$(get-admin-relative-dir ${SSL_CLIENT_DIR})"
    echo "SSL_CTL_DIR=$(get-admin-relative-dir ${SSL_CTL_DIR})"
    echo "SSL_SNMP_DIR=$(get-admin-relative-dir ${SSL_SNMP_DIR})"
    echo "SSL_VAR_DIR=$(get-admin-relative-dir ${SSL_VAR_DIR})"

    echo "WAF_DIR=$(get-admin-relative-dir ${WAF_DIR})"
    echo "VPN_IPSEC_DIR=$(get-admin-relative-dir ${VPN_IPSEC_DIR})"
    echo "URLLIST_DIR=$(get-admin-relative-dir ${URLLIST_DIR})"
    echo "SSH_PUBLIC_KEY_DIR=$(get-admin-relative-dir ${SSH_PUBLIC_KEY_DIR})"

    echo "URLLIST_VAR_DIR=$(get-admin-relative-dir ${URLLIST_VAR_DIR})"
    echo "AV_VAR_DIR=$(get-admin-relative-dir ${AV_VAR_DIR})"
    echo "RUN_DIR=$(get-admin-relative-dir ${RUN_DIR})"

    echo "SSH_MANAGER_RSA_FP_FILE=$(get-admin-relative-dir ${SSH_MANAGER_RSA_FP_FILE})"

    echo "WAF_DIR_NAME=${WAF_DIR_NAME}"
    echo "VPN_IPSEC_DIR_NAME=${VPN_IPSEC_DIR_NAME}"
    echo "URLLIST_DIR_NAME=${URLLIST_DIR_NAME}"
    echo "SSL_DIR_NAME=${SSL_DIR_NAME}"
    echo "PUBLIC_DIR_NAME=${PUBLIC_DIR_NAME}"

    echo "ADMIN_DIR=/home/${ADMIN_NAME}"
    echo "DOC_COMMAND_DIR=/${DOC_DIR_NAME}/${DOC_COMMAND_DIR_NAME}"
    echo "GUI_DASHBOARD_CORE_EXT=${GUI_DASHBOARD_CORE_EXT}"
    echo "GUI_DIR=${GUI_DIR}"
    echo "GUI_CGI_DIR=${GUI_CGI_DIR}"
    echo "APPLIANCE_DIR=${APPLIANCE_DIR}"
    echo "ETC_HTML_DIR=${GUI_DIR}/${ETC_HTML_RDIR}"
    echo "MIB_DIR=/${MIB_DIR_NAME}"
    echo "BASE_DIR=/home"

    echo "DEFAULT_SHOSTNAME=${TECHNICAL_NAME}"
    echo "DEFAULT_DOMAIN_NAME=example.com"
    echo "WADMIN_TERM=${WADMIN_TERM}"
    echo "SETUP=${SETUP}"
    echo "TRANSACTION_FILE=${TRANSACTION_FILE}"
    echo "MAIN_MIB_NAME=${MAIN_MIB_NAME}"

    echo "HOME_NAME=${HOME_NAME}"

    echo "GUI_MOSAIC_LIMIT_LEFT=${GUI_MOSAIC_LIMIT_LEFT}"
    echo "GUI_MOSAIC_LIMIT_TOP=${GUI_MOSAIC_LIMIT_TOP}"
    echo "GUI_MOSAIC_WIDTH=${GUI_MOSAIC_WIDTH}"
    echo "GUI_MOSAIC_HEIGHT=${GUI_MOSAIC_HEIGHT}"
    echo "GUI_MOSAIC_GRID_STICK=${GUI_MOSAIC_GRID_STICK}"

    echo "COMMAND_PATH=${APPLIANCE_DIR}/bin:${APPLIANCE_DIR}/lib"
    echo "PATH=\${COMMAND_PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    echo "MANAGER_CONF_CONTEXT_FILE=${MANAGER_CONF_CONTEXT_FILE}"
    echo "MANAGER_EXEC_CONTEXT_FILE=${MANAGER_EXEC_CONTEXT_FILE}"
    echo "MANAGER_EXEC_COMMANDS_FILE=${MANAGER_EXEC_COMMANDS_FILE}"
    echo "MANAGER_PUSHED=${MANAGER_PUSHED}"

    echo "APPLIANCE_PASSWD=${APPLIANCE_PASSWD}"

    echo "ACCESS_VPN_ID='access'"

    echo "DYNAMIC_DNS_PROVIDERS='changeip dnshome freemyip myonlineportal noip'"
    echo "DEFAULT_DYNAMIC_DNS_PROVIDER=freemyip"

    echo "MIN_DYNAMIC_DNS_INTERVAL=1"
    echo "MAX_DYNAMIC_DNS_INTERVAL=30"
    echo "MAX_TLS_CA_NB=256"
    echo "MAX_AV_WHITELIST_DOMAINNAME_NB=256"
    echo "MAX_AV_WHITELIST_REGEX_NB=256"
    echo "MAX_SSLMEDIATE_EXCEPTIONS_DOMAINNAME_NB=256"
    echo "MAX_GUARD_FILTERS_NB=32"
    echo "MAX_GUARD_POLICIES_NB=32"
    echo "MAX_GUARD_RULES_NB=64"
    echo "MAX_FW_RULES_NB=256"
    echo "MAX_QOS_SHAPE_ROUTER_RULES_NB=256"
    echo "MAX_IP_ROUTES_NB=128"
    echo "MAX_MULTI_GATEWAYS=15"
    echo "MAX_IP_DEFAUKT_ROUTES_NB=15"
    echo "MAX_VPN_NETWORK_NB=256"
    echo "MAX_RWEB_HOST_NB=64"
    echo "MAX_NAME_SERVER_NB=8"
    echo "MAX_NTP_SERVER_NB=8"
    echo "MAX_LDAP_SERVER_NB=8"
    echo "MAX_KERBEROS_SERVER_NB=8"
    echo "MAX_PEERS_NB=64"
    echo "MAX_VRRP_NB=16"
    echo "MAX_TRANSPARENT_WEB_NB=64"
    echo "MAX_ACL_WEB_NB=64"
    echo "MAX_ACL_RWEB_NB=64"
    echo "MAX_ACL_ADMIN_NB=16"
    echo "MAX_ACL_FILE_NB=16"
    echo "MAX_ACL_MON_NB=16"
    echo "MAX_ACL_AV_NB=32"
    echo "MAX_ACL_MANAGER_NB=2"
    echo "MAX_BOND_NB=4"
    echo "MAX_DHCP_RANGE_NB=256"
    echo "MAX_DHCP_FIXED_NB=256"
    echo "MAX_DHCP_PEER_NB=1"
    echo "MAX_SNMP_TRAP_NB=8"
    echo "MAX_SYSLOG_NB=8"
    echo "MAX_SAN_CERT_NB=32"
    echo "MAX_WAF_BYPASS_NB=512"
    echo "MAX_WAF_SCORE=25"
    echo "MAX_USER_LEN=24"
    echo "MAX_COOKIE_LEN=16"
    echo "MAX_LEN=64"
    echo "MAX_FILENAME_LEN=128"
    echo "MAX_URL_LEN=256"
    echo "MAX_LDAP_DN_LEN=256"
    echo "MAX_LDAP_FILTER_LEN=384"
    echo "MAX_VPN_IPSEC_TO=8"
    echo "MAX_VPN_IPSEC_BEHIND_NAT_IP_NB=8"
    echo "MAX_NAME_IP_NB=256"
    echo "MAX_IKE_ID_LEN=192"

    echo "CACHE_MIN_OBJECT_SZ_MIN=1"
    echo "CACHE_MAX_OBJECT_SZ_MIN=1"
    echo "CACHE_MAX_OBJECT_SZ_MAX=$[256 * 1024]"
    echo "AV_MAX_FILE_MIN=1024"
    echo "AV_MAX_FILE_MAX=24576"
    echo "OCSP_DAYS_MIN=1"
    echo "OCSP_DAYS_MAX=31"
    echo "TLS_DAYS_MIN=1"
    echo "TLS_DAYS_MAX=7310"
    echo "WAF_DOS_COUNTER_MAX=1000000"
    echo "WAF_DOS_SLICE_MAX=86400"
    echo "WAF_DOS_TIMEOUT_MAX=604800"
}

gen-apl-constant()
{
    local mode=${1}

    gen-common-constant

    case ${mode} in
	''|dev)
	    echo "APL_MODEL=${APL_MODEL}"
	    case ${APL_MODEL} in
		'test')
		    echo "TEST_SRC_PROTOCOL=${TEST_SRC_PROTOCOL}"
		    echo "TEST_SRC_IP=${TEST_SRC_IP}"
		    echo "TEST_SRC_ACCOUNT=${TEST_SRC_ACCOUNT}"
		    echo "TEST_SRC_DIR=${TEST_SRC_DIR}"
		    ;;
		*)
		    ;;
	    esac
	    ;;
    esac

    echo "LVM_VG_NAME=${LVM_VG_NAME}"
    echo "LVM_PE_SZ=${LVM_PE_SZ}"
    echo "LVM_MD_SZ=${LVM_MD_SZ}"
    echo "LICENSE_PERIOD_MARGIN_2=${LICENSE_PERIOD_MARGIN_2}"

    echo "SYS_VERSION=${SYS_VERSION}"
    echo "SYS_RELEASE_NAME=${SYS_RELEASE_NAME}"
    echo "SYS_NAME=${SYS_NAME}"
    echo "SYS_HM_NAME=${SYS_HM_NAME}"
    echo "SYS_64_NAME=${SYS_64_NAME}"
    echo "SYS_UML_NAME=${SYS_UML_NAME}"
    echo "SYS_UML_64_NAME=${SYS_UML_64_NAME}"
    echo "SYS_RAMDISK_SIZE=${SYS_RAMDISK_SIZE}"

    echo "SERIAL_SPEED=${SERIAL_SPEED}"
    echo "TRUSTED_TTY='${TRUSTED_TTY}'"
    echo "BINKEYMAP_DIR_NAME=${BINKEYMAP_DIR_NAME}"
    echo "PATH=${PATH}"
    echo "SHELL=${SHELL}"

    echo "OS_VERSION=${OS_VERSION}"
    echo "PUBLIC_WEB_SERVER_NAME='${PUBLIC_WEB_SERVER_NAME}'"
    echo "GUARD_FTP_SERVER=${GUARD_FTP_SERVER}"

    echo "AV_DOMAIN_NAME=av.cacheguard.net"
    echo "OS_WEBSITE=${OS_WEBSITE}"
    echo "REGISTER_APL_URL=${REGISTER_APL_URL}"
    echo "REGISTER_SN_URL=${REGISTER_SN_URL}"
    echo "REGISTER_CHECK_URL=${REGISTER_CHECK_URL}"
    echo "ALIVE_CHECK_URL=${ALIVE_CHECK_URL}"

    echo "GEO_LITE_COUNTRY_URL=${GEO_LITE_COUNTRY_URL}"
    echo "AZURE_NETWORK_IP_URL=${AZURE_NETWORK_IP_URL}"
    echo "AWS_NETWORK_IP_URL=${AWS_NETWORK_IP_URL}"

    echo "NAMED_UID=${NAMED_UID}"
    echo "NAMED_GID=${NAMED_GID}"
    echo "SQUID_UID=${SQUID_UID}"
    echo "SQUID_GID=${SQUID_GID}"
    echo "HTTPD_UID=${HTTPD_UID}"
    echo "HTTPD_GID=${HTTPD_GID}"
    echo "AV_UID=${AV_UID}"
    echo "AV_GID=${AV_GID}"
    echo "IPSEC_UID=${IPSEC_UID}"
    echo "IPSEC_GID=${IPSEC_GID}"

    echo "AV_USER=${AV_USER}"
    echo "AV_GROUP=${AV_GROUP}"
    echo "IPSEC_USER=${IPSEC_USER}"

    echo "CLOUD_DIR=${CLOUD_DIR}"
    echo "CLOUD_RESOLV_DIR=${CLOUD_RESOLV_DIR}"

    echo "NAMED_DIR=${NAMED_DIR}"
    echo "KERBEROS_CACHE_DIR=${KERBEROS_CACHE_DIR}"
    echo "KERBEROS_KEYTAB_FILE_PROXY1=${KERBEROS_KEYTAB_FILE_PROXY1}"
    echo "KERBEROS_KEYTAB_FILE_PROXY2=${KERBEROS_KEYTAB_FILE_PROXY2}"

    echo "AV_UPDATE_DATE=${AV_UPDATE_DATE}"
    echo "AV_DB_DIR=${AV_DB_DIR}"
    echo "AV_EXTENDED_CACHE_DIR=${AV_EXTENDED_CACHE_DIR}"
    echo "AV_EXTENDED_CACHE_DB_DIR=${AV_EXTENDED_CACHE_DB_DIR}"
    echo "AV_EXTENDED_PACK_NAME=${AV_EXTENDED_PACK_NAME}"
    echo "CLAMAV_TMP_DIR_PREFIX=tmp."
    echo "AV_STREAM_MIN_PORT=${AV_STREAM_MIN_PORT}"
    echo "AV_STREAM_MAX_PORT=${AV_STREAM_MAX_PORT}"

    echo "AUDIT_NAME=${AUDIT_NAME}"
    echo "STANDBY_NAME=${STANDBY_NAME}"

    echo "ERROR_LOCATION=${ERROR_LOCATION}"
    echo "URL_DENIED_URI='${URL_DENIED_URI}'"
    echo "AV_DENIED_URI='${AV_DENIED_URI}'"
    echo "ACCESS_WARNING_URI=${ACCESS_WARNING_URI}"
    echo "WEB_GATEWAY_URI=${WEB_GATEWAY_URI}"
    echo "CGI_MESSAGE_FILE=${CGI_MESSAGE_FILE}"

    echo "RUNTIME_ENV_DIR=${RUNTIME_ENV_DIR}"

    echo "PROXY_CACHE_DIR=${PROXY_CACHE_DIR}"
    echo "PROXY_LOG_DIR=${PROXY_LOG_DIR}"
    echo "PROXY_SSL_SERVER_DIR=${PROXY_SSL_SERVER_DIR}"
    echo "PROXY_RUN_DIR=${PROXY_RUN_DIR}"
    echo "PROXY_SSL_CA_DIR=${PROXY_SSL_CA_DIR}"
    echo "PROXY_SSL_SERVER_DIR=${PROXY_SSL_SERVER_DIR}"
    echo "PROXY_SSL_LOCAL_CA_DIR=${PROXY_SSL_LOCAL_CA_DIR}"
    echo "PROXY_DB_DIR=${PROXY_DB_DIR}"
    echo "PROXY_DB_SSL_DIR=${PROXY_DB_SSL_DIR}"
    echo "PROXY_GUARD_DIR=${PROXY_GUARD_DIR}"
    echo "PROXY_DOMAIN_LIST_DIR=${PROXY_DOMAIN_LIST_DIR}"
    echo "PROXY_EXPRESSION_LIST_DIR=${PROXY_EXPRESSION_LIST_DIR}"
    echo "PROXY_STATE_DIR=${PROXY_STATE_DIR}"

    echo "WEB_MESSAGE_DIR=${WEB_MESSAGE_DIR}"
    echo "WEB_VAR_DIR=${WEB_VAR_DIR}"
    echo "WEB_CACHE_DIR=${WEB_CACHE_DIR}"
    echo "WEB_RCACHE_DIR=${WEB_RCACHE_DIR}"
    echo "WEB_UPLOAD_DIR=${WEB_UPLOAD_DIR}"
    echo "WEB_WWW_DIR=${WEB_WWW_DIR}"
    echo "WEB_CA_DIR=${WEB_CA_DIR}"
    echo "WEB_LOG_DIR=${WEB_LOG_DIR}"
    echo "WEB_RUN_DIR=${WEB_RUN_DIR}"
    echo "WEB_SSL_DIR=${WEB_SSL_DIR}"
    echo "WEB_SSL_CA_DIR=${WEB_SSL_CA_DIR}"
    echo "WEB_DB_DIR=${WEB_DB_DIR}"
    echo "WEB_WAF_DIR=${WEB_WAF_DIR}"

    echo "IPSEC_DIR=${IPSEC_DIR}"
    echo "IPSEC_SSL_CA_DIR=${IPSEC_SSL_CA_DIR}"

    echo "HOME_DIR=${HOME_DIR}"
    echo "SN_DIR=${SN_DIR}"
    echo "ADMIN_DIR=${ADMIN_DIR}"
    echo "MANAGER_DIR=${MANAGER_DIR}"
    echo "VAR_DIR=${VAR_DIR}"
    echo "ETC_DIR=${ETC_DIR}"
    echo "HARD_DIR=${HARD_DIR}"
    echo "TMP_DIR=${TMP_DIR}"
    echo "TMP_TEMPLATE_DIR=${TMP_TEMPLATE_DIR}"
    echo "TMP_GATEWAY_DIR=${TMP_GATEWAY_DIR}"
    echo "LOG_DIR=${LOG_DIR}"
    echo "MANAGER_LOG_DIR=${MANAGER_LOG_DIR}"
    echo "RUN_DIR=${RUN_DIR}"
    echo "DB_DIR=${DB_DIR}"

    echo "SSL_DIR=${SSL_DIR}"
    echo "SSL_CA_DIR=${SSL_CA_DIR}"
    echo "SSL_LOCAL_CA_DIR=${SSL_LOCAL_CA_DIR}"
    echo "SSL_SERVER_DIR=${SSL_SERVER_DIR}"
    echo "SSL_CLIENT_DIR=${SSL_CLIENT_DIR}"
    echo "SSL_CTL_DIR=${SSL_CTL_DIR}"
    echo "SSL_SNMP_DIR=${SSL_SNMP_DIR}"
    echo "SSL_VAR_DIR=${SSL_VAR_DIR}"

    echo "WAF_DIR=${WAF_DIR}"
    echo "VPN_IPSEC_DIR=${VPN_IPSEC_DIR}"
    echo "URLLIST_DIR=${URLLIST_DIR}"
    echo "SSH_PUBLIC_KEY_DIR=${SSH_PUBLIC_KEY_DIR}"

    echo "INTERMEDIATE_CA=${INTERMEDIATE_CA}"
    echo "URLLIST_VAR_DIR=${URLLIST_VAR_DIR}"
    echo "AV_VAR_DIR=${AV_VAR_DIR}"
    echo "SAVE_DIR=${SAVE_DIR}"
    echo "LOCK_DIR=${LOCK_DIR}"
    echo "BASE_DIR=${BASE_DIR}"
    echo "ABASE_DIR=${ABASE_DIR}"

    echo "APPLIANCE_PHP_DIR=${APPLIANCE_PHP_DIR}"
    echo "APPLIANCE_DIR=${ADMIN_DIR}${APPLIANCE_DIR}"
    echo "LDAP_DIR=${LDAP_DIR}"
    echo "SNMP_SSL_CA_DIR=${SNMP_SSL_CA_DIR}"
    echo "SNMP_SSL_CERTIFICATE_DIR=${SNMP_SSL_CERTIFICATE_DIR}"
    echo "SNMP_SSL_KEY_DIR=${SNMP_SSL_KEY_DIR}"
    echo "CACHEGUARD_DIR=${CACHEGUARD_DIR}"
    echo "CONF_DIR=${CONF_DIR}"
    echo "CONF_RUN_DIR=${CONF_RUN_DIR}"

    echo "DB_SCHEMA_DIR=${DB_SCHEMA_DIR}"
    echo "VPN_IPSEC_ACCESS_DB_FILE=${VPN_IPSEC_ACCESS_DB_FILE}"
    echo "VPN_IPSEC_ACCESS_DB_SCHEMA=${VPN_IPSEC_ACCESS_DB_SCHEMA}"

    echo "AV_EXTENDED_CRON_FILENAME=${AV_EXTENDED_CRON_FILENAME}"
    echo "DYNAMIC_DNS_CRON_FILENAME=${DYNAMIC_DNS_CRON_FILENAME}"

    echo "LDAP_CA=${LDAP_CA}"

    echo "WWW_DIR_NAME=${WWW_DIR_NAME}"
    echo "GUI_ERRORS_FILE=${GUI_ERRORS_FILE}"
    echo "GUI_DIR=${ADMIN_DIR}${GUI_DIR}"
    echo "GUI_HTML_DIR=${GUI_HTML_DIR}"
    echo "CGI_RDIR=${CGI_RDIR}"
    echo "RWEB_AUDIT_DIR=${RWEB_AUDIT_DIR}"
    echo "WAUDIT_DIR=${WAUDIT_DIR}"
    echo "ETC_HTML_RDIR=/${ETC_HTML_RDIR}"

    echo "SUSPEND=${SUSPEND}"
    echo "SUSPEND_BACKUP=${SUSPEND_BACKUP}"
    echo "SN_SN=${SN_SN}"

    echo "LIC_GATEWAY_MIN=${LIC_GATEWAY_MIN}"
    echo "LIC_GATEWAY_MAJ=${LIC_GATEWAY_MAJ}"
    echo "LIC_MANAGER_MIN=${LIC_MANAGER_MIN}"
    echo "LIC_MANAGER_MAJ=${LIC_MANAGER_MAJ}"

    echo "WAUTH_LOG=${WAUTH_LOG}"
    echo "APPLY_LOG=${APPLY_LOG}"
    echo "CACHE_CLEAR_LOG=${CACHE_CLEAR_LOG}"
    echo "AV_CREATE_LOG=${AV_CREATE_LOG}"
    echo "AV_UPDATE_LOG=${AV_UPDATE_LOG}"
    echo "LOG_ROTATE_LOG=${LOG_ROTATE_LOG}"
    echo "URLLIST_AUTO_LOG=${URLLIST_AUTO_LOG}"
    echo "BACKUP_LOG=${BACKUP_LOG}"
    echo "KERBEROS_CREATE_LOG=${KERBEROS_CREATE_LOG}"
    echo "AV_AUTO_UPDATE_FILE=${AV_AUTO_UPDATE_FILE}"
    echo "MANAGER_PULL_OPERATION_LOG=${MANAGER_PULL_OPERATION_LOG}"
    echo "MANAGER_PUSH_OPERATION_LOG=${MANAGER_PUSH_OPERATION_LOG}"
    echo "MANAGER_TEMPLATE_EXEC_OPERATION_LOG=${MANAGER_TEMPLATE_EXEC_OPERATION_LOG}"
    echo "MANAGER_LOCAL_EXEC_OPERATION_LOG=${MANAGER_LOCAL_EXEC_OPERATION_LOG}"
    echo "MANAGER_REMOTE_EXEC_OPERATION_LOG=${MANAGER_REMOTE_EXEC_OPERATION_LOG}"
    echo "MANAGER_SYNC_FILE=${MANAGER_SYNC_FILE}"
    echo "CLOUD_NETWORK_IP_FILE=${CLOUD_NETWORK_IP_FILE}"

    echo "WEB_SERVER_DENY_NAME=${WEB_SERVER_DENY_NAME}"
    echo "COSS_FILENAME=${COSS_FILENAME}"
    echo "SERVICES_HEALTH_FILENAME=${SERVICES_HEALTH_FILENAME}"

    echo "IF_EXTERNAL_NUM=${IF_EXTERNAL_NUM}"
    echo "IF_INTERNAL_NUM=${IF_INTERNAL_NUM}"
    echo "IF_AUXILIARY_NUM=${IF_AUXILIARY_NUM}"

    echo "SNMP_OID=${SNMP_OID}"
    echo "PROXY_LOG=${PROXY_LOG}"
    echo "PROXY_GUARD_LOG=${PROXY_GUARD_LOG}"
    echo "WEB_SERVER_LOG=${WEB_SERVER_LOG}"
    echo "WAF_DEBUG_LOG=${WAF_DEBUG_LOG}"

    echo "WAF_RULE_ID_INIT=1000000"
    echo "WAF_CUSTOM_RULE_ID_INIT=2000000"

    echo          "QOS_MARK_MASK=0x00000fff"
    echo "ROUTE_TPROXY_MARK_MASK=0x00001000"
    echo      "ROUTE_TPROXY_MARK=0x00001000"
    echo        "IPSEC_MARK_MASK=${IPSEC_MARK_MASK}"
    echo          "IPSEC_IN_MARK=${IPSEC_IN_MARK}"
    echo         "IPSEC_OUT_MARK=${IPSEC_OUT_MARK}"
    echo        "ROUTE_MARK_MASK=0x000f0000"
    echo "ROUTE_INIT_MARK=1"

    local route_mark_mask="0x000f0000"
    local right_zeros=${route_mark_mask/*f}
    echo "ROUTE_MARK_SHIFT=$[${#right_zeros} * 4]"

    echo "IPSEC_CONNECTION_DIR_NAME=${IPSEC_CONNECTION_DIR_NAME}"

    echo "STARTUP_BACKUP_DIR=/root"
    echo "ETHERNET_BACKUP_INDEX_FILENAME=ethernet-backup-index"
    echo "CACHE_RECONFIGURE_BACKUP_FILENAME=squid-backup-reconfigure.conf"

    echo "FW_LOG_TAG=${FW_LOG_TAG}"
    echo "KERBEROS_PASSWORD_VALIDITY_DAYS=${KERBEROS_PASSWORD_VALIDITY_DAYS}"

    echo "PARTITION_LABEL_TYPE=${PARTITION_LABEL_TYPE}"
    echo "EFI_SZ=${EFI_SZ}"
    echo "FIRST_PARTITION_BEGINING_SECTOR=${FIRST_PARTITION_BEGINING_SECTOR}"
    echo "GRUB_PARTITION_NB=${GRUB_PARTITION_NB}"
    echo "EFI_PARTITION_NB=${EFI_PARTITION_NB}"
    echo "ROOT_PARTITION_NB=${ROOT_PARTITION_NB}"
    echo "OS_DISK_LVM_PARTITION_NB=${OS_DISK_LVM_PARTITION_NB}"
    echo "NOS_DISK_LVM_PARTITION_NB=${NOS_DISK_LVM_PARTITION_NB}"
    echo "RAID_PARTITION_NB=${RAID_PARTITION_NB}"
    echo "RAID_ROOT_PARTITION_NB=${RAID_ROOT_PARTITION_NB}"
    echo "RAID_LVM_PARTITION_NB=${RAID_LVM_PARTITION_NB}"
    echo "RAID_MD_NB=${RAID_MD_NB}"

    echo "SSH_HOST_RSA_KEY_FILE=${SSH_HOST_RSA_KEY_FILE}"
    echo "SSH_MANAGER_RSA_FP_FILE=${SSH_MANAGER_RSA_FP_FILE}"

    echo "IPTABLES_POLICY_ROUTING_CHAIN=POLICYROUTING"
    echo "IPTABLES_STICKY_DEFAULT_ROUTE_CHAIN=STICKYDEFAULTROUTE"
    echo "IPTABLES_STICKY_EXTERNAL_ROUTE_CHAIN=STICKYEXTERNALROUTE"
    echo "IPTABLES_RUNTIME_MANGLE_SDEFAULT_ROUTE=${CONF_RUN_DIR}/iptables.policy.route.sdefault"
    echo "IPTABLES_RUNTIME_MANGLE_EXTERNAL_ROUTE=${CONF_RUN_DIR}/iptables.policy.route.external"
    echo "IPTABLES_RUNTIME_MANGLE_INDEX=${CONF_RUN_DIR}/iptables.policy.route.index"

    echo "CLOUD_METADATA_IP=${CLOUD_METADATA_IP}"
    echo "CLOUD_AZURE_FABRIC_IP=${CLOUD_AZURE_FABRIC_IP}"

    echo "UDEV_RULES_DIR=/etc/udev/rules.d"
    echo "UDEV_NETWORK_RULES_FILE_NAME=70-persistent-net.rules"

    echo "SUPERADMIN_DIR=${SUPERADMIN_DIR}"

    echo "IPSEC_ROUTE_TABLE_NB=${IPSEC_ROUTE_TABLE_NB}"
    echo "IPSEC_ROUTE_TABLE_NAME=${IPSEC_ROUTE_TABLE_NAME}"
    echo "IPSEC_ROUTE_PRIORITY=${IPSEC_ROUTE_PRIORITY}"

    echo "TRANSPARENT_ROUTE_TABLE_NB=${TRANSPARENT_ROUTE_TABLE_NB}"
    echo "TRANSPARENT_ROUTE_TABLE_NAME=${TRANSPARENT_ROUTE_TABLE_NAME}"
    echo "TRANSPARENT_ROUTE_PRIORITY=${TRANSPARENT_ROUTE_PRIORITY}"

    echo "TPROXY_ROUTE_TABLE_NB=${TPROXY_ROUTE_TABLE_NB}"
    echo "TPROXY_ROUTE_TABLE_NAME=${TPROXY_ROUTE_TABLE_NAME}"
    echo "TPROXY_ROUTE_PRIORITY=${TPROXY_ROUTE_PRIORITY}"

    echo "ROUTE_INIT_PRIORITY=${ROUTE_INIT_PRIORITY}"

    echo "CONFIGURATION_DB_SCHEMA=${CONFIGURATION_DB_SCHEMA}"

    echo "EMBEDDED_APPLICATION_IP=127.0.0.2"
    echo "EMBEDDED_REGISTER_URL=${EMBEDDED_REGISTER_URL}"

    echo "EMBEDDED_VPNSUBSCR_VERSION=${EMBEDDED_VPNSUBSCR_VERSION}"
    echo "EMBEDDED_VPNSUBSCR_PROFILE_DIR_NAME=${EMBEDDED_VPNSUBSCR_PROFILE_DIR_NAME}"
    echo "EMBEDDED_VPNSUBSCR_DB_FILE=${EMBEDDED_VPNSUBSCR_DB_FILE}"
    echo "EMBEDDED_VPNSUBSCR_PORT=81"
    echo "EMBEDDED_VPNSUBSCR_LIC_KEY=${EMBEDDED_VPNSUBSCR_LIC_KEY}"
    echo "EMBEDDED_VPNSUBSCR_LIC_MIN=${EMBEDDED_VPNSUBSCR_LIC_MIN}"
    echo "EMBEDDED_VPNSUBSCR_LIC_MAJ=${EMBEDDED_VPNSUBSCR_LIC_MAJ}"
    echo "EMBEDDED_VPNSUBSCR_NEW_ACCOUNT_URL=${EMBEDDED_VPNSUBSCR_NEW_ACCOUNT_URL}"
    echo "EMBEDDED_VPNSUBSCR_PUSH_EMAIL_URL=${EMBEDDED_VPNSUBSCR_PUSH_EMAIL_URL}"
}

gen-constant-files()
{
    gen-apl-constant "${@}" > ${GENERATED_DIR}/constant
    gen-admin-constant > ${GENERATED_DIR}/admin.constant
}

install-constant()
{
    sudo install -m 444 -o root -g root ${GENERATED_DIR}/constant ${APL}${CACHEGUARD_DIR}/constant
    sudo install -m 444 -o root -g root ${GENERATED_DIR}/admin.constant ${APL}${ADMIN_DIR}${APPLIANCE_DIR}/etc/constant
}

install-modules()
{
    local mode=${1}

    local cur_dir=${PWD}

    for module in ${SOURCES_MODULES}
    do
	test -f ${module}/install.bash || continue
	echo "+++ Installing ${module}..."
	cd ${module}
	./install.bash ${mode}
	cd ${cur_dir}
    done
}

# Main()

mkdir -p ${FULL_GENERATED_DIR}
ln -sf ${FULL_GENERATED_DIR}

SOURCES_MODULES="Documentation Shared Scripts ETC Tuner Commands GUI Embedded Configurator InitScripts"

gen-constant-files "${@}"
install-constant
install-modules "${@}"
