Cancel new settings
.SH SYNOPSIS

[1] \fBcancel\fR

.SH DESCRIPTION
This command is used to cancel a new configuration before its application with the command
.B apply.
The usage of different commands does not immediately affect the running system. A new configuration is applied only when the command
.B apply
is used. It is always possible to cancel all new settings by using this command.
.SH SEE ALSO
.B apply
(1)
.B conf
(1)
