Display valid country codes
.SH SYNOPSIS

[1] \fBcountrylist\fR

.SH DESCRIPTION
This command displays all ISO 3166-1 alpha-2 country codes. You can use this command to find the code for a particular country. The country code retrieved here is to be used as an argument for commands such as "\fBantivirus country\fR \fI<country-code>\fR" or "\fBwaf reputation country\fR \fI<country-code>\fR".

.SH SEE ALSO
.B antivirus
(1)
.B waf
(1)
