Set or get the local domain name
.SH SYNOPSIS

[1] \fBdomainname\fR [\fI<name>\fR]

.SH DESCRIPTION
This command is used to get or set the local domain name. The argument <name> must be a valid domain name. A valid domain name is a string beginning with an alphabetic character and containing a combination of alpha-numeric characters, the character "-" and the character ".".
.SH SEE ALSO
.B apply
(1)
