Display descriptions of error codes returned by commands
.SH SYNOPSIS

[1] \fBerror\fR [\fI<error-code>\fR]

.SH DESCRIPTION
Use this command to display the description of all error codes return by commands. You can also display the description of a particular error by giving its code (\fI<error-code>\fR). This command can be very useful if for any reasons displayed errors are not fully displayed by commands.

.SH SEE ALSO
.B manager
(1)
