Print command's usage and description
.SH SYNOPSIS

[1] \fBhelp\fR [\fI<command-name>\fR]

.SH DESCRIPTION
Without any argument the
.B help
command displays a brief description of all available commands (this manual). If a
.I <command-name>
is given as argument, the manual of the given command is displayed.

.SH SYNTAX & TYPOGRAPHY
When typing commands in a terminal the
.I <TAB>
key allow you to complete the typing keyword and to display allowed arguments. Us it always to remember the syntax of commands.

In manuals, the syntax of command utilisation is given using some simple rules. When different choices are available the character
.B "|"
is used to separate choices. Parenthesis 
.I (
and
.I )
are used to specify without any ambiguity the order of keywords and arguments. They are not part of the command. Optional arguments are given inside brackets
.I [
and
.I ].

Command names and keywords are given in
.B bold.
Arguments are in
.I italic.

After reading an online command help, type "q" to quit the help command.

.SH ALL COMMANDS
Here are a brief description of all available commands:

