Set or get the hostname
.SH SYNOPSIS

[1] \fBhostname\fR [\fI<name>\fR]

.SH DESCRIPTION
This command is used to get or to set the host name. The argument <name> must be a valid host name. A valid host name is a string beginning with an alphanumeric character and containing a combination of alphanumeric characters, the dash ("\fI-\fR")  and dot ("\fI.\fR") characters.

.SH SEE ALSO
.B apply
(1)
