Display descriptions of information codes returned by commands
.SH SYNOPSIS

[1] \fBinformation\fR [\fI<information-code>\fR]

.SH DESCRIPTION
Use this command to display the description of all information codes return by commands. You can also display the description of a particular information by giving its code (\fI<information-code>\fR). This command can be very useful if for any reasons displayed informations are not fully displayed by commands.

.SH SEE ALSO
.B manager
(1)
