Print a report on the current running operation in background
.SH SYNOPSIS

[1] \fBjob\fR

.SH DESCRIPTION
Some operations like the the apply or the cache clearing operations are executed in background. During those operations the configuration is locked and no other background operation can be executed. The \fBjob\fR command without any arguments (first [1] usage form) prints a report on the current running operation in background.

.SH SEE ALSO
.B antivirus
(1)
.B apply
(1)
.B cache
(1)
.B file
(1)
.B ha
(1)
.B halt
(1)
.B log
(1)
.B reboot
(1)
.B system
(1)
