Manage passwords
.SH SYNOPSIS

[1] \fBpassword\fR [\fBconsole\fR | (\fBlogin\fR | \fBwadmin\fR) [\fI<current-password>\fR [\fI<new-password>\fR]]]

[2] \fBpassword file\fR [((\fBadd\fR (\fBftp\fR | \fBsftp\fR) \fI<file-server>\fR \fI<login>\fR [\fI<password>\fR]) | (\fBdel\fR \fI<file-server>\fR) | \fBraz\fR)]

[3] \fBpassword ldap\fR [\fI<password>\fR]

[4] \fBpassword snmp\fR (\fBcommunity\fR | \fBprivacy\fR) [\fI<password>\fR]

[5] \fBpassword kerberos\fR [\fI<shared-password>\fR]

[6] \fBpassword email\fR [\fI<password>\fR]

.SH DESCRIPTION
The first [1] usage form is used to update the administrator's authenticating token. To update the console or the SSH login password, use the keyword \fBconsole\fR. To update the Web GUI password use the keyword \fBwadmin\fR. To update both the console and Web GUI passwords use the keyword \fBlogin\fR. If no keyword is specified, the \fBlogin\fR keyword is selected by default. The length of a valid password should be at least 16 characters and less than 33. It is highly recommended to use a pass phrase that includes alphanumeric and special characters.


Please note that administrator passwords are not part of the configuration and thus are not saved when the configuration is saved.

The second [2] usage form is used to manage file server logins and passwords (see the \fBaccess\fR command).

The third [3] usage form is used to set the password to access LDAP servers. LDAP servers are used to authenticate users (see the \fBauthenticate\fR and \fBmode\fR commands). This is useful only if access to LDAP servers is protected by a password. Classically this is the LDAP administrator's password. Do not confuse this password with passwords required by users for authentication.

To set the DN (Distinguished Name) of the top LDAP node which requires a password use the command \fBauthenticate\fR.

The fourth [4] usage form is used to set the SNMP agent community password. The minimum SNMP password length is 8 characters. To set the SNMP v3 user name of the SNMP agent use the command \fBadmin\fR.

The fifth [5] usage form allows you to set the shared password to use for the kerberos account associated to the present system. This setting is only used if the system is in an HA configuration (with two or more redundant nodes). Please note that in an HA configuration, the same password should be used on all HA nodes.

The sixth [6] usage form is used to set the password for the administrator email account. The administrator email account is used by the system to send some configuration files by email (see the \fBemail\fR command).

In all cases if no password is specified, you will be prompted to enter the password in hidden mode. Note that to take effect, the \fBapply\fR command must be used after password modifications (except for administration passwords).

.SH SEE ALSO
.B access
(1)
.B admin
(1)
.B authenticate
(1)
.B apply
(1)
.B email
(1)
.B mode
(1)
.B waf
(1)
