Send ICMP packets to network hosts
.SH SYNOPSIS

[1] \fBping\fR (\fI<name>\fR | \fI<ip>\fR)

.SH DESCRIPTION
Ping uses the ICMP protocol's mandatory ECHO_REQUEST datagram to elicit an ICMP ECHO_RESPONSE from a host or gateway. Use this command to check the network connectivity and name resolution by CacheGuard.

.SH SEE ALSO
.B traceroute
(1)
