Reboot the system
.SH SYNOPSIS

[1] \fBreboot\fR [\fBforce\fR]

.SH DESCRIPTION
Use this command to reboot the system. Without the optional argument \fBforce\fR the user is invited to confirm the reboot action. The optional argument \fBforce\fR allows you to bypass this confirmation.

.SH SEE ALSO
.B halt
(1)
