Performs a basic startup configuration
.SH SYNOPSIS

[1] \fBsetup\fR

.SH DESCRIPTION
This command performs a basic startup configuration by:

* Phase 1: Asking you pertinent questions to set up your basic configuration.

* Phase 2: Executing online commands with your inputs.

* Phase 3: Applying the configuration with the command \fBapply\fR.

This command is automatically executed when you first connect to the system.

.SH SEE ALSO
.B access
(1)
.B admin
(1)
.B apply
(1)
.B dns
(1)
.B ip
(1)
.B port
(1)
.B mode
(1)
