Trace the route to a host
.SH SYNOPSIS

[1] \fBtraceroute\fR (\fI<name>\fR | \fI<ip>\fR) [\fBicmp\fR | \fBudp\fR]

.SH DESCRIPTION
You can use this command to trace the route to a host specified by its IP address or name. This command uses the ICMP protocol by default. You can use the UDP protocol on the 33434 port by using the \fBudp\fR optional argument.

.SH SEE ALSO
.B ping
(1)
