Manage the transparent Web proxy
.SH SYNOPSIS

[1] \fBtweb\fR [\fBraz\fR | (\fBadd\fR (\fBinternal\fR | \fBauxiliary\fR | \fBvpnipsec\fR) \fI<ip>\fR [\fI<network-mask>\fR [\fI<qos>\fR]]) | (\fBdel\fR (\fBinternal\fR | \fBauxiliary\fR | \fBvpnipsec\fR) \fI<ip>\fR \fI<network-mask>\fR)]

.SH DESCRIPTION

See the \fBtransparent\fR command manual.
