Display descriptions of warning codes returned by commands
.SH SYNOPSIS

[1] \fBwarning\fR [\fI<warning-code>\fR]

.SH DESCRIPTION
Use this command to display the description of all warning codes return by commands. You can also display the description of a particular warning by giving its code (\fI<warning-code>\fR). This command can be very useful if for any reasons displayed warnings are not fully displayed by commands.

.SH SEE ALSO
.B manager
(1)
