eap-ttls {
    fragment_size = 1024
    include_length = yes
    load = yes
    max_message_count = 0
    phase2_method = psk
    phase2_piggyback = no
    phase2_tnc = no
    phase2_tnc_method = pt
    request_peer_auth = no
}
