eap-radius {
    accounting = no
    accounting_close_on_timeout = yes
    accounting_interval = 0
    accounting_requires_vip = no
    accounting_send_class = no
    class_group = no
    close_all_on_timeout = no
    eap_start = no
    filter_id = no
    id_prefix =
    load = no
    nas_identifier = CacheGuard
    port = 1812
    retransmit_base = 1.4
    retransmit_timeout = 2.0
    retransmit_tries = 4
    secret =
    server =
    sockets = 1
    station_id_with_port = yes

    dae {
        enable = no
        listen = 0.0.0.0
        port = 3799
        secret =
    }

    forward {
        ike_to_radius =
        radius_to_ike =
    }

    servers {
    }

    xauth {
    }
}
