eap-peap {
    fragment_size = 1024
    include_length = no
    load = yes
    max_message_count = 0
    phase2_method = mschapv2
    phase2_piggyback = no
    phase2_tnc = no
    request_peer_auth = no
}
