tnc-ifmap {
    client_cert =
    client_key =
    device_name =
    load = no
    renew_session_interval = 150
    server_cert =
    server_uri = https://localhost:8444/imap
    username_password =
}
