tnc-pdp {
    load = no
    server =
    timeout =

    pt_tls {
        enable = yes
        port = 271
    }

    radius {
        enable = no
        method = ttls
        port = 1812
        secret =
    }
}
