charon {
    accept_private_algs = no
    accept_unencrypted_mainmode_messages = no
    block_threshold = 5
    cache_crls = no
    cert_cache = yes
    cisco_unity = no
    close_ike_on_child_failure = no
    cookie_threshold = 10
    delete_rekeyed = no
    delete_rekeyed_delay = 5
    dh_exponent_ansi_x9_42 = yes
    dlopen_use_rtld_now = no
    dns1 =
    dns2 =
    dos_protection = yes
    ecp_x_coordinate_only = yes
    flush_auth_cfg = no
    follow_redirects = yes
    fragment_size = 1280
    group =
    half_open_timeout = 30
    hash_and_url = no
    i_dont_care_about_security_and_use_aggressive_mode_psk = no
    ignore_acquire_ts = no
    ignore_routing_tables =
    ikesa_limit = 0
    ikesa_table_segments = 1
    ikesa_table_size = 1
    inactivity_close_ike = no
    init_limit_half_open = 0
    init_limit_job_load = 0
    initiator_only = no
    install_routes = yes
    install_virtual_ip = no
    install_virtual_ip_on =
    integrity_test = no
    interfaces_ignore =
    interfaces_use =
    keep_alive = 20s
    load =
    load_modular = yes
    make_before_break = no
    max_ikev1_exchanges = 3
    max_packet = 10000
    multiple_authentication = no
    nbns1 =
    nbns2 =
    port = 500
    port_nat_t = 4500
    prefer_best_path = no
    prefer_configured_proposals = yes
    prefer_temporary_addrs = no
    process_route = no
    rdn_matching = strict
    receive_delay = 0
    receive_delay_request = yes
    receive_delay_response = yes
    receive_delay_type = 0
    replay_window = 32
    retransmit_base = 1.1
    retransmit_jitter = 0
    retransmit_limit = 3
    retransmit_timeout = 3.0
    retransmit_tries = 3
    retry_initiate_interval = 0
    reuse_ikesa = yes
    routing_table =
    routing_table_prio =
    rsa_pss = no
    send_delay = 0
    send_delay_request = yes
    send_delay_response = yes
    send_delay_type = 0
    send_vendor_id = no
    signature_authentication = yes
    signature_authentication_constraints = yes
    spi_label = 0x0000000000000000
    spi_mask = 0x0000000000000000
    spi_max = 0xcfffffff
    spi_min = 0xc0000000
    threads = 16
    user =

    crypto_test {
	bench = no
	bench_size = 1024
        bench_time = 50
        on_add = no
        on_create = no
        required = no
        rng_true = no
    }

    host_resolver {
            max_threads = 3
            min_threads = 0
    }

    leak_detective {
         detailed = yes
         usage_threshold = 10240
         usage_threshold_count = 0
    }

    processor {
        priority_threads {
        }
    }

    start-scripts {
    }

    stop-scripts {
    }

    tls {
        cipher = 
        key_exchange = 
        mac = 
        suites =
    }

    x509 {
        enforce_critical = yes
    }
}
