charon {
    filelog {
    }

    syslog {
	identifier = vpnipsec
	auth {
	    dmn = 0
	    mgr = 0
	    ike = 0
	    chd = 0
	    job = 0
	    cfg = 0
	    knl = 0
	    net = 0
	    asn = 0
	    enc = 0
	    tls = 0
	    esp = 0
	    lib = 0
	    tnc = 0
	    imc = 0
	    imv = 0
	    pts = 0
	    default = 0
	    ike_name = no
	    map_level = -1
	}
    }
}
