ha {
    autobalance = 0
    fifo_interface = yes
    heartbeat_delay = 1500
    heartbeat_timeout = 3000
    load = no
    local =
    monitor = yes
    pools =
    remote =
    resync = yes
    secret = jsE1xsHqP973!S4gAmcE@
    segment_count = 1
}
